Ucl 199 - BaseStyling component docs & addon
onewelcome/react-lib-components pull request #236
Opened 2022-10-31 10:02 UTC by Danielvandervelden

2022-11-02 06:42 UTC, pawel-napieracz requested changes
When I'm changing primary color on `Button` page, and then I go to `DataGrid` I don't see styles to by applied to `DataGrid` :(.

2022-11-02 10:08 UTC, pawel-napieracz commented on .storybook/addon/src/components/PanelContent.tsx
> +  "colorFocus",
it's worth to mention in `BaseStyling` that we need to add new variables also here :)

2022-11-02 10:11 UTC, pawel-napieracz commented on .storybook/addon/src/components/PanelContent.tsx
> +  };
```suggestion
  const handlePropertyChange = (propertyName: string, propertyValue: string) => 
    setPropertiesState((prevState: Record<string, string>) => ({
      ...prevState,
      [propertyName]: propertyValue
    }));
```

2022-11-02 10:16 UTC, pawel-napieracz commented on .storybook/addon/src/components/PanelContent.tsx
> +  const renderContent = () => {
we don't need to have `rows`, since we can just render on `propertiesState` right?

```
const rows = (propertiesState && Object.entries(propertiesState) ?? []).map(([key, propertyValue]) => (<tr key={property}>
            <td>{key}</td>
            <td style={{ textAlign: "left" }}>
              <PropertyValueLabel>{key}</PropertyValueLabel>
              {shouldBeColorPicker.includes(key) ? (
                <ColorControl
                  name={key}
                  onChange={value => {
                    handlePropertyChange(property, value);
                  }}
                  value={parseValue(propertyValue)}
                />
              ) : (
                <PropertyValueInput
                  onChange={e => handlePropertyChange(key, e.target.value)}
                  type="text"
                  value={parseValue(propertyValue)}
                />
              )}
            </td>
          </tr>)
```

2022-11-02 10:17 UTC, pawel-napieracz commented on .storybook/addon/src/utils/helpers.ts
> +export const CSSPropertyToObjectKey = (CSSProperty: string) => {
the method name should start from lower-case`cssPropertyToObjectKey`

2022-11-02 10:17 UTC, pawel-napieracz commented on .storybook/addon/src/utils/helpers.ts
> +export const ObjectKeyToCSSProperty = ({ key, value }: { key: string; value: string }) => {
same here

2022-11-02 10:18 UTC, pawel-napieracz commented on .storybook/addon/src/withBaseStyling.ts
> +    }, 1);
please extract `1` to const that have a meaningful name, telling why we want to wait 1ms ;)

2022-11-02 10:18 UTC, pawel-napieracz commented on .storybook/addon/src/withBaseStyling.ts
> +        console.log(stylesObject, "STYLEOBJECT");
remove it :)

2022-11-02 10:27 UTC, pawel-napieracz commented on .storybook/addon/src/withBaseStyling.ts
> +    return propertiesObject;
why not 
```
propertiesArray.reduce((propertiesObj, property) => {...propertiesObj, [property] = CSSPropertyToObjectKey(property).value}, {})
```
?

2022-11-02 10:27 UTC, pawel-napieracz commented on .storybook/addon/src/withBaseStyling.ts
> +    for (const property in stylingObject) {
why not `Object.entries(stylingObject).reduce`?

2022-11-02 10:30 UTC, pawel-napieracz commented on .storybook/addon/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
why yarn file? Shouldn't it be `package-json.lock`?

2022-11-02 10:34 UTC, pawel-napieracz commented on .storybook/preview.tsx
> +    if (baseStylingSessionStorage !== "undefined" && baseStylingSessionStorage) {
```suggestion
    if (baseStylingSessionStorage && baseStylingSessionStorage !== "undefined") {
```
seams more readable, don't u think so?

2022-11-02 10:45 UTC, pawel-napieracz commented on src/mixins.module.scss
> +  @include focusOutline(var(--color-focus));
I don't think it's a good name for color.
Because it's a rather `color-outline`, not `color-focus`. WDYT?

2022-11-02 10:48 UTC, pawel-napieracz commented on stories/BaseStyling/BaseStyling.stories.mdx
> +Down below you will find all of the CSS properties that are currently supported and an explanation of what they do, and which components they affect.
```suggestion
Down below, you will find all of the CSS properties that are currently supported and an explanation of what they do and which components they affect.
```

2022-11-02 10:50 UTC, pawel-napieracz commented on stories/BaseStyling/BaseStyling.stories.mdx
> +Will get translated to the CSS variable `--color-focus`. By default this refers to the same color as `--color-primary`, so if you change the `--color-primary` variable to a different color, this prop
```suggestion
Will get translated to the CSS variable `--color-focus`. By default, this refers to the same color as `--color-primary`, so if you change the `--color-primary` variable to a different color, this property will automatically change as well.
```

2022-11-02 10:52 UTC, pawel-napieracz commented on stories/BaseStyling/BaseStyling.stories.mdx
> +Will get translated to the CSS variable `--success`. This is the success color, used for the [StatusIndicator component](/story/components-feedback-statusindicator--status-indicator) and the checkmar
```suggestion
Will get translated to the CSS variable `--success`. This is the success color used for the [StatusIndicator component](/story/components-feedback-statusindicator--status-indicator) and the checkmark in the top left of an individual [Tile Component](/story/components-layout-tiles-tiles--tiles).
```

2022-11-02 10:53 UTC, pawel-napieracz commented on stories/BaseStyling/BaseStyling.stories.mdx
> +Will get translated to the CSS variable `--error`. It' used in **all** components inside the `Inputs` category when there's an error, and also inside the [StatusIndicator component](/story/components
```suggestion
Will get translated to the CSS variable `--error`. It's used in **all** components inside the `Inputs` category when there's an error and also inside the [StatusIndicator component](/story/components-feedback-statusindicator--status-indicator&args=status:error) when it's set to `Error`.
```

2022-11-02 12:59 UTC, Danielvandervelden commented on .storybook/addon/package.json
> +  "author": "Daniel <daniel.vandervelden@onewelcome.com>",
DAMNIT, it adds that automatically I swear xD

2022-11-02 13:00 UTC, Danielvandervelden commented on .storybook/addon/package.json
> +  "license": "MIT",
Good point, let me do that to each file.

2022-11-02 13:07 UTC, Danielvandervelden commented on .storybook/addon/src/components/PanelContent.tsx
> +  "colorFocus",
Good point, fixed.

2022-11-02 13:08 UTC, Danielvandervelden commented on .storybook/addon/src/components/PanelContent.tsx
> +  };
Couldn't commit the suggestion because it was outdated, have done so in a separate commit myself.

2022-11-02 13:10 UTC, Danielvandervelden commented on .storybook/addon/src/components/PanelContent.tsx
> +  const renderContent = () => {
Rows needs to be a state variable, because it needs to rerender whenever it changes. I'm not sure if I understand what you're trying to say :D?

2022-11-02 13:12 UTC, Danielvandervelden commented on .storybook/addon/src/utils/helpers.ts
> +export const ObjectKeyToCSSProperty = ({ key, value }: { key: string; value: string }) => {
done

2022-11-02 13:14 UTC, Danielvandervelden commented on .storybook/addon/src/withBaseStyling.ts
> +    }, 1);
Extracted and made comment to check readme technical explanation section as to why it's necessary.

2022-11-02 13:14 UTC, Danielvandervelden commented on .storybook/addon/src/withBaseStyling.ts
> +        console.log(stylesObject, "STYLEOBJECT");
Wasn't me, I promise.

2022-11-02 13:16 UTC, Danielvandervelden commented on .storybook/addon/src/withBaseStyling.ts
> +    return propertiesObject;
Because generally `reduce` also reduces (xD) readability.

2022-11-02 13:16 UTC, Danielvandervelden commented on .storybook/addon/src/withBaseStyling.ts
> +    for (const property in stylingObject) {
See previous comment regarding reduce

2022-11-02 13:18 UTC, Danielvandervelden commented on .storybook/addon/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
I copied the entire addon template from a repo (https://github.com/storybookjs/addon-kit) they used yarn, so I did too. Even though npm should work just the same I think

2022-11-02 13:20 UTC, Danielvandervelden commented on src/mixins.module.scss
> +  @include focusOutline(var(--color-focus));
It was colorFocus before already. I don't know who implemented it 😄 . Let's do this discussion of variable names inside of https://onewelcome.atlassian.net/browse/UCL-212 WDYT?

2022-11-02 13:20 UTC, Danielvandervelden commented on stories/BaseStyling/BaseStyling.stories.mdx
> +Down below you will find all of the CSS properties that are currently supported and an explanation of what they do, and which components they affect.
Done

2022-11-02 14:50 UTC, pawel-napieracz commented on .storybook/addon/src/components/PanelContent.tsx
> +  const renderContent = () => {
but you can do rerender on `propertiesState` change. You don't need to set in in state xD.
`rows` is only read only state and it's rendered when `propertiesState` changed ;)

2022-11-02 14:50 UTC, pawel-napieracz commented on .storybook/addon/src/components/PanelContent.tsx
> +  const renderContent = () => {
also you can use `map` method to render it ;)

2022-11-02 14:53 UTC, pawel-napieracz commented on .storybook/addon/src/withBaseStyling.ts
> +    return propertiesObject;
for me it's more readable :). If you know how reduce works then you pray to have it where it fits xD

2022-11-02 14:53 UTC, pawel-napieracz commented on .storybook/addon/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
in readme you have npm. Also there is `package-json.lock`. Please decide what to keep ;)

2022-11-03 06:45 UTC, Danielvandervelden commented on .storybook/addon/src/components/PanelContent.tsx
> +  const renderContent = () => {
Done

2022-11-03 06:45 UTC, Danielvandervelden commented on .storybook/addon/src/withBaseStyling.ts
> +    return propertiesObject;
I know how it works, I just don't think it's as readable 😛. But for me it's fine, I'll change it to reduce if that makes you happy 😄

2022-11-03 07:07 UTC, Danielvandervelden commented on .storybook/addon/src/withBaseStyling.ts
> +    for (const property in stylingObject) {
Actually, I realised I'm not doing anything with this StyleString... the HTML element style tag is being set by our BaseStyling component 😄. Removed redundant code and changed function name.

2022-11-03 07:09 UTC, Danielvandervelden commented on stories/BaseStyling/BaseStyling.stories.mdx
> +Will get translated to the CSS variable `--success`. This is the success color, used for the [StatusIndicator component](/story/components-feedback-statusindicator--status-indicator) and the checkmar
✅

2022-11-03 07:09 UTC, Danielvandervelden commented on stories/BaseStyling/BaseStyling.stories.mdx
> +Will get translated to the CSS variable `--error`. It' used in **all** components inside the `Inputs` category when there's an error, and also inside the [StatusIndicator component](/story/components
✅

2022-11-03 08:18 UTC, Danielvandervelden commented on .storybook/addon/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Done, we use NPM

2022-11-03 08:35 UTC, pawel-napieracz requested changes

2022-11-03 08:35 UTC, pawel-napieracz commented on .storybook/addon/src/components/PanelContent.tsx
> +      return [].map(([key, value]) => (
does it works :O?
empty array map xD?
Shouldn't it be like that `Object.entries(propertiesState).map` xD?

2022-11-03 09:00 UTC, pawel-napieracz approved these changes

2022-11-03 09:13 UTC, merged