UCL-144 Add support for CSS reduced-motion setting
onewelcome/react-lib-components pull request #254
Opened 2022-11-21 11:23 UTC by MichalGorskiOnegini

2022-11-24 07:00 UTC, pawel-napieracz requested changes
skeleton now has very weird animation. Should we also reduce animation for skeleton animation xD?
And if so, can't we just turn off animations rather than setting 0.1ms duration?

@jashaj WDYT?

2022-11-24 07:00 UTC, pawel-napieracz commented
> skeleton now has very weird animation. Should we also reduce animation for skeleton animation xD? And if so, can't we just turn off animations rather than setting 0.1ms duration?

2022-11-24 07:21 UTC, jashaj commented
@pawel-napieracz. The skeleton shouldn't visibly animate. There was a technical reason why turning off animations wouldn't work. @MichalGorskiOnegini can explain you why.

2022-11-25 08:48 UTC, pawel-napieracz approved these changes

2022-11-25 08:48 UTC, pawel-napieracz approved these changes

2022-11-25 08:49 UTC, merged