UCL-291 Add github pages support
onewelcome/react-lib-components pull request #257
Opened 2022-12-01 10:33 UTC by MichalGorskiOnegini

2022-12-06 07:38 UTC, jashaj commented on catalog-info.yaml
>    type: other
type: library

2022-12-06 07:38 UTC, jashaj commented on catalog-info.yaml
>    lifecycle: unknown
lifecycle: production?

2022-12-06 07:38 UTC, jashaj commented on catalog-info.yaml
>    links:
Should the release URL point to GitHub pages?

2022-12-06 07:39 UTC, jashaj commented on catalog-info.yaml
> +  description: React component library
React component library for what? :-)

2022-12-06 07:58 UTC, jashaj commented on README.md
> +[![OneWelcome](https://circleci.com/gh/onewelcome/react-lib-components.svg?style=svg)](<https://circleci.com>)
The alt text is incorrect here. Should be `CircleCI status`

2022-12-06 08:27 UTC, jashaj commented on .circleci/config.yml
> +          command: git remote set-url origin https://git:${GITHUB_API_TOKEN}@github.com/onewelcome/react-lib-components.git
Can you verify that it does not print the actual API token in log files?

2022-12-06 08:29 UTC, jashaj commented on package.json
> +    "github-pages:deploy": "gh-pages -d storybook-static -u \"github-actions-bot <support+actions@github.com>\""
IMO this part of the package.json should move to the CircleCI config. We don't want people to manually deploy docs. Suggestion: https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/

2022-12-13 13:22 UTC, MichalGorskiOnegini commented on catalog-info.yaml
>    links:
for now, let's leave it as is. In the near future we might completely move to gh pages with it (or somewhere else)

2022-12-30 07:03 UTC, pawel-napieracz requested changes

2022-12-30 07:03 UTC, pawel-napieracz commented on catalog-info.yaml
>    lifecycle: unknown
@MichalGorskiOnegini ?

2022-12-30 07:05 UTC, MichalGorskiOnegini commented on catalog-info.yaml
>    lifecycle: unknown
I'm not sure so I did not change it

2022-12-30 07:07 UTC, pawel-napieracz approved these changes

2022-12-30 07:07 UTC, merged