UCL-214 - Fix popover position on scroll + performance
onewelcome/react-lib-components pull request #269
Opened 2022-12-14 11:48 UTC by Danielvandervelden

2022-12-16 12:35 UTC, MichalGorskiOnegini requested changes

2022-12-16 12:35 UTC, MichalGorskiOnegini commented on src/Popover/Popover.tsx
> +    window.addEventListener("resize", determineIfExecuteCalculatePosition);
can't we just wrap adding/removing in `if` statement? This way we would only add the event listener when it's actually visible. In addition, we could fix the name from the ambiguous `determineIfExecuteCalculatePosition` to `calculatePosition`

2022-12-16 12:35 UTC, MichalGorskiOnegini commented on src/Popover/Popover.tsx
> +      (top === 0 ||
Can you help me out understand what it means? Why are we checking those values? (not a tricky question I just don't understand :D )

2022-12-16 12:35 UTC, MichalGorskiOnegini commented on src/hooks/usePosition.ts
> +  debounceAmount: 15
What is it for?

2022-12-16 12:35 UTC, MichalGorskiOnegini commented on src/ContextMenu/ContextMenu.tsx
>    return (
**GENERAL COMMENT**

Overall it looks much better, but it still keeps stuttering a lot. Is this something that can be further improved, or is it too time-consuming?

2022-12-19 08:10 UTC, Danielvandervelden commented on src/Popover/Popover.tsx
> +    window.addEventListener("resize", determineIfExecuteCalculatePosition);
This was actually sort of leftover after a try with using `useDebouncedCallback` for this function. Removed it and only applying listener when `show` is `true`.

2022-12-19 08:12 UTC, Danielvandervelden commented on src/Popover/Popover.tsx
> +      (top === 0 ||
So, as soon as `top`, `left`, `right` or `bottom` is 0, it means that the `anchorEl` (meaning the element you click on to show the Popover) has moved off screen. In this case, you want to close the Popover menu. It wouldn't make sense to just have it floating there at the bottom or top while the element that triggers it is somewhere offscreen.

2022-12-19 08:18 UTC, Danielvandervelden commented on src/hooks/usePosition.ts
> +  debounceAmount: 15
Debouncing limits the amount of function executions. So let's say you're scrolling. Normally, ever single pixel you scroll the function would get executed. However, now it will check `has it been this long since I stopped scrolling` and THEN execute it. This way, we save performance by not executing the function constantly, but only at the end of an action.

I've added it to the configuration props, because sometimes people don't like this and want to be able to configure it.

2022-12-19 08:19 UTC, Danielvandervelden commented on src/ContextMenu/ContextMenu.tsx
>    return (
The stuttering is caused because we are limiting the amount of callbacks being called. Do we want to lower it so it's smoother but less performant?

2022-12-19 10:12 UTC, MichalGorskiOnegini commented on src/ContextMenu/ContextMenu.tsx
>    return (
@jashaj WDYT?

2022-12-19 10:15 UTC, MichalGorskiOnegini commented on src/Popover/Popover.tsx
> +    if (!show) return;
nit

this would be way more readable with braces IMO

2022-12-19 10:16 UTC, MichalGorskiOnegini commented on src/Popover/Popover.tsx
> +      (top === 0 ||
makes sense, can we move this to a variable then? I would call it: `isOffscreen`?

2022-12-20 08:12 UTC, Danielvandervelden commented on src/Popover/Popover.tsx
> +    if (!show) return;
I guess this is a backend thing. Pawel also doesn't like it, but I really do because it's nice and short and simply a `guard` for whatever code comes after it 😛. But I'll surround it instead of using the guard method.

2022-12-20 08:50 UTC, Danielvandervelden commented on src/Popover/Popover.tsx
> +      (top === 0 ||
Done

2022-12-20 11:27 UTC, MichalGorskiOnegini commented on src/hooks/usePosition.ts
> +  debounceAmount: 15
nice

2022-12-20 11:27 UTC, MichalGorskiOnegini commented on src/Popover/Popover.tsx
> +    if (!show) return;
discussed on slack

2022-12-20 11:28 UTC, MichalGorskiOnegini approved these changes

2022-12-20 11:28 UTC, merged