UCL-153 Clean up eslint rules
onewelcome/react-lib-components pull request #296
Opened 2023-01-03 12:34 UTC by MichalGorskiOnegini

2023-01-04 09:37 UTC, Danielvandervelden requested changes

2023-01-04 09:37 UTC, Danielvandervelden commented on src/DataGrid/DataGridActions/DataGridActions.tsx
> +            {addBtnProps.children ? addBtnProps.children : "Add item"}
```suggestion
            {addBtnProps.children ??  "Add item"}
```

2023-01-04 09:37 UTC, Danielvandervelden commented on src/DataGrid/DataGridActions/DataGridActions.tsx
> +              {columnsBtnProps.children ? columnsBtnProps.children : "Columns"}
```suggestion
              {columnsBtnProps.children ??  "Columns"}
```

2023-01-04 09:37 UTC, Danielvandervelden commented on src/DataGrid/DataGridActions/DataGridActions.tsx
> +              {searchBtnProps.children ? searchBtnProps.children : "Search"}
```suggestion
              {searchBtnProps.children ??  "Search"}
```

2023-01-04 09:37 UTC, Danielvandervelden commented on src/Tabs/TabButton.test.tsx
> +const defaultParams: Props = { title: "Title" };
Should we test this prop?

2023-01-04 09:37 UTC, Danielvandervelden commented on src/Tabs/TabButton.tsx
> +  { children, tabActive, focused, title, ...rest }: Props,
Now children prop is not used. Why did you change it to `title`?

2023-01-04 09:41 UTC, pawel-napieracz requested changes

2023-01-04 09:41 UTC, pawel-napieracz commented on .eslintrc.js
> +        "react/no-children-prop": "warn", //we want to have freedom in that case
shouldn't it be error? If we want to it only few times I'd opt for:
```
// eslint-disable-line react/display-name
or 
// eslint-disable-next-line react/display-name
```

2023-01-04 09:41 UTC, pawel-napieracz commented on src/DataGrid/DataGridActions/DataGridActions.tsx
> +            {addBtnProps.children ? addBtnProps.children : "Add item"}
It's still in `addBtnProps` under the `children` prop which you use in line 74.
Are we going to leave it there?
If not then you can do

```
const {children: addBtnChildren, ...restAddButtonProps } = addBtnProps
```

2023-01-04 09:41 UTC, pawel-napieracz commented on src/DataGrid/DataGridActions/DataGridActions.tsx
> +              {columnsBtnProps.children ? columnsBtnProps.children : "Columns"}
maybe the same issue?

2023-01-04 09:41 UTC, pawel-napieracz commented on src/DataGrid/DataGridActions/DataGridActions.tsx
> +              {searchBtnProps.children ? searchBtnProps.children : "Search"}
maybe the same issue?

2023-01-04 09:41 UTC, pawel-napieracz commented on src/Tabs/Tabs.tsx
> +          children
Why are you passing children if you don't use it in that component 😄 ?

2023-01-04 12:03 UTC, MichalGorskiOnegini commented on src/DataGrid/DataGridActions/DataGridActions.tsx
> +            {addBtnProps.children ? addBtnProps.children : "Add item"}
😮

2023-01-04 12:05 UTC, MichalGorskiOnegini commented on .eslintrc.js
> +        "react/no-children-prop": "warn", //we want to have freedom in that case
I only followed what was on the ticket. With regards to display name, it did not require any changes to the codebase, as it's done automatically by React.

2023-01-04 13:45 UTC, MichalGorskiOnegini commented on src/Tabs/TabButton.tsx
> +  { children, tabActive, focused, title, ...rest }: Props,
Because, in reality, this was never a children, but a title. But you have some valid points, I will rewrite this a bit.

2023-01-04 13:52 UTC, MichalGorskiOnegini commented on src/Tabs/Tabs.tsx
> +          children
Good point. I will most likely revert this.

2023-01-04 13:55 UTC, MichalGorskiOnegini commented on src/Tabs/TabButton.test.tsx
> +const defaultParams: Props = { title: "Title" };
removed

2023-01-04 19:13 UTC, pawel-napieracz commented on .eslintrc.js
> +        "react/no-children-prop": "warn", //we want to have freedom in that case
`warn` lvl does not fails build. That's why I opt for `error` and if someone wants it they can disable eslint for that particular rule for one line.

2023-01-16 05:13 UTC, pawel-napieracz approved these changes

2023-01-16 05:17 UTC, merged