UCL-29 Add <Banner /> component
onewelcome/react-lib-components pull request #316
Opened 2023-01-12 14:55 UTC by AndreeaIlieThales

Add Banner component to the 
Story for reference Feedback list of components.
Story for reference: https://onewelcome.atlassian.net/browse/UCL-29
![Screenshot 2023-01-12 at 15 53 39](https://user-images.githubusercontent.com/122360490/212099144-dc85f104-0943-4e1e-b285-8e16b328baa6.png)

2023-01-16 10:07 UTC, szmejk requested changes

2023-01-16 12:43 UTC, AndreeaIlieThales commented on src/Notifications/Banner/Banner.tsx
> +  ariaRole?: string;
Ah cool. Ty

2023-01-16 12:44 UTC, AndreeaIlieThales commented on stories/BaseStyling/BaseStyling.stories.mdx
> +Will get translated to the CSS variable `--info`. It's used in [Banner component]() // TODO
Nah, forgotten there, thank you for pointing it up

2023-01-18 07:16 UTC, szmejk approved these changes

2023-01-18 07:16 UTC, merged