UCL-167 Extends input for success icon/indicator
onewelcome/react-lib-components pull request #323
Opened 2023-01-17 12:45 UTC by AndreeaIlieThales

Story for ref: https://onewelcome.atlassian.net/jira/software/c/projects/UCL/boards/211?selectedIssue=UCL-167
<img width="1262" alt="Screenshot 2023-01-17 at 13 44 51" src="https://user-images.githubusercontent.com/122360490/212902267-56d1d416-d4a3-4307-8ac8-3eed359fb961.png">

2023-01-19 11:06 UTC, Danielvandervelden requested changes

2023-01-19 13:14 UTC, AndreeaIlieThales commented on src/Form/Input/Input.module.scss
>  .input-wrapper [data-suffix] {
oops ^^

2023-01-19 15:32 UTC, AndreeaIlieThales commented on src/Form/Input/Input.module.scss
> +  color: var(--success);
should be fixed now

2023-01-20 11:00 UTC, Danielvandervelden requested changes

2023-01-20 11:00 UTC, Danielvandervelden commented on src/Form/Input/Input.module.scss
>    height: 100%;
Seems to still be 18px for the `Input` component, could you check 🙂

2023-01-20 11:00 UTC, Danielvandervelden commented on src/Form/Input/Input.module.scss
>  .input-wrapper [data-suffix] {
Could you see if you can get the alignment between the icon and the suffix right when a value is entered 🙂 
![Screenshot 2023-01-20 at 11 39 48](https://user-images.githubusercontent.com/20994699/213676056-025859c4-c9d2-430a-915f-58e3844cb204.png)

2023-01-20 11:00 UTC, Danielvandervelden commented on src/hooks/useDetermineStatusIcon.tsx
> +  params: FormElement,
I understand why you might want to use the `FormElement` interface here (because it has `success` and `error`), but what if this interface will be extended later on with some other props? That would mean it's not valid anymore. I'd say it's better to specifically ask for the error and success boolean value here.

2023-01-20 11:00 UTC, Danielvandervelden commented on src/hooks/useDetermineStatusIcon.tsx
> +  successIconClassName: string[]
Since we are rendering once of two icons and want to possibly add styles to it we could also go another route than to pass classes.  Everywhere we use the hook, it seems to be giving the classes `error-icon` and `success-icon`, which means that we use the same class everywhere to reference them.

Instead of needing to pass classes we can also omit that entire extra configuration (saving us a few micromilliseconds 😄 ) and add like a `data` attribute to each of the icons (`data-status-icon="error"` or success for the other one).

The only thing we'll need to make sure now is that the selectors inside of the `*.module.scss` files `[data-status-icon="error"] { ...stylerules }` are nested inside of their parent class so they don't get globally applied.

2023-01-20 11:00 UTC, Danielvandervelden commented on src/hooks/useDetermineStatusIcon.tsx
> + *    You may obtain a copy of the License at
Could you add tests for this hook?

2023-01-20 11:03 UTC, AndreeaIlieThales commented on src/hooks/useDetermineStatusIcon.tsx
> +  params: FormElement,
It's true is should be a partial of FormElement

2023-01-20 11:04 UTC, Danielvandervelden commented
It also seems the textarea label has a white background that the checkmark icon disappears behind when you resize the window/textarea:
![Screenshot 2023-01-20 at 11 38 12](https://user-images.githubusercontent.com/20994699/213680493-131bf08b-2733-4d98-a16f-3bf442e03202.png)

2023-01-20 11:13 UTC, AndreeaIlieThales commented on src/hooks/useDetermineStatusIcon.tsx
> +  successIconClassName: string[]
It feels a bit like using the wrong selectors. In this regard, I could just as well return an Icon with a className of 'success-icon' and 'error-icon'. Perhaps I could make these method params optional though, and return for each '<status>-icon' className joined with whatever classNames the method would be decorated with, if that happens

2023-01-20 11:46 UTC, AndreeaIlieThales commented on src/Form/Input/Input.module.scss
>    height: 100%;
That's strange. The font size for the input icons has changed. It's true, they are measured in relative sizes, and if we wanted them straight out 20px, I would replace the font sizing with px, but it still shouldn't be 18px like before to you

2023-01-23 10:15 UTC, Danielvandervelden requested changes

2023-01-23 10:15 UTC, Danielvandervelden commented on src/hooks/useDetermineStatusIcon.tsx
> +    icon = <Icon ref={errorRef} className="error-icon" icon={Icons.Error} />;
So the big problem now is that all the `*.module.scss` files generate scoped classnames. These `error-icon` and `success-icon` classes won't get styled by your `*.module.scss` files, because they're not global.

This is why I suggested `[data]` attributes, because these can actually be styled globally inside a `*.module.scss` file 😄 



![Screenshot 2023-01-23 at 11 09 01](https://user-images.githubusercontent.com/20994699/214013776-86cc0000-9b17-49dd-8338-f6a14b80f34f.png)

2023-01-24 07:16 UTC, Danielvandervelden approved these changes

2023-01-24 07:16 UTC, merged