UCL-128 Adjust spacing for mobile resolutions
onewelcome/react-lib-components pull request #378
Opened 2023-02-13 14:24 UTC by MichalGorskiOnegini

2023-02-15 06:20 UTC, pawel-napieracz requested changes

2023-02-15 06:20 UTC, pawel-napieracz commented on src/Form/Wrapper/InputWrapper/InputWrapper.tsx
> +  const helperIndent = window.innerWidth > 479 ? 20 : 16;
you need to take a font-size from document.body and calculate px as browsers does with rems.

2023-02-15 06:20 UTC, pawel-napieracz commented on src/Form/Wrapper/SelectWrapper/SelectWrapper.module.scss
> +    margin-top: 0.25rem;
margin-top is not needed

2023-02-15 06:20 UTC, pawel-napieracz commented on stories/Form/Form.stories.tsx
> +  chromatic: { viewports: [400, 1200] }
I'm glad you did it only for one story :). Coole we have one story that has all form elements

2023-02-20 08:24 UTC, MichalGorskiOnegini commented on src/Form/Fieldset/Fieldset.module.scss
> +  padding: 1rem var(--form-element-horizontal-padding-mobile);
you are correct, my bad :D

2023-02-20 09:02 UTC, MichalGorskiOnegini commented on stories/Form/Form.stories.tsx
> +  chromatic: { viewports: [400, 1200] }
indeed ;)

2023-02-20 09:03 UTC, MichalGorskiOnegini commented on src/Form/Wrapper/SelectWrapper/SelectWrapper.module.scss
> +    margin-top: 0.25rem;
oops

2023-02-20 13:52 UTC, MichalGorskiOnegini commented on src/Form/Wrapper/InputWrapper/InputWrapper.tsx
> +  const helperIndent = window.innerWidth > 479 ? 20 : 16;
done

2023-02-24 11:24 UTC, pawel-napieracz approved these changes

2023-02-24 11:24 UTC, pawel-napieracz commented on src/Form/Wrapper/InputWrapper/InputWrapper.tsx
> +  const helperIndent = window.innerWidth > remToPx(30) ? remToPx(1.25) : remToPx(1);
fixed

2023-02-28 08:24 UTC, merged