UCL-262 Cleanup non-quantum color variables
onewelcome/react-lib-components pull request #525
Opened 2023-04-27 06:38 UTC by MichalGorskiOnegini

2023-04-27 10:47 UTC, pawel-napieracz requested changes

2023-04-27 10:47 UTC, pawel-napieracz commented on src/Form/FileUpload/FileUpload.module.scss
> +      var(--color-primary300),
border: bluegray-500,
background: bluegray-25

2023-04-27 10:47 UTC, pawel-napieracz commented on src/Form/FileUpload/FileItem/FileItem.modules.scss
> -    background-color: var(--light-pink);
maybe it should be: black-10?

2023-04-27 10:47 UTC, pawel-napieracz commented on src/Form/FileUpload/FileItem/FileItem.modules.scss
> -    background-color: var(--light-pink);
https://www.figma.com/file/zAzyG3fmBFKrdrVzFeEYAv/Quantum---2.-%F0%9F%8C%9E-Light-Components?node-id=12076-286905&t=JVKQYe5hvfU0OeJQ-0

2023-04-27 10:47 UTC, pawel-napieracz commented on stories/BaseStyling/BaseStyling.stories.mdx
> -## dragBackgroundColor
couldn't do it in line 51, but would be nice to sync that list.
Also we have these colors in our plugin. Please update our properties there as well (see comment in `BaseStyling.tsx:18`)

2023-04-27 10:47 UTC, pawel-napieracz commented on stories/BaseStyling/BaseStyling.stories.mdx
> -## dragBackgroundColor
And don't remove that paraghaph plx :D

2023-04-27 12:41 UTC, MichalGorskiOnegini commented on src/Form/FileUpload/FileItem/FileItem.modules.scss
> -    background-color: var(--light-pink);
ok

2023-05-04 04:40 UTC, pawel-napieracz requested changes

2023-05-04 04:40 UTC, pawel-napieracz commented on src/_BaseStyling_/BaseStyling.tsx
> +    dragBackgroundColor: "var(--color-blue-grey25-transparent)",
you don't use that color :(

2023-05-04 04:40 UTC, pawel-napieracz commented on stories/BaseStyling/BaseStyling.stories.mdx
> -## grey
please add in docs missing colors + sync /.storybook/addon/src/components/PanelContent.tsx

2023-05-04 09:51 UTC, pawel-napieracz approved these changes

2023-05-04 10:44 UTC, merged