UCL-248 update all packages, remove DTS, custom rollup config
onewelcome/react-lib-components pull request #546
Opened 2023-05-05 13:41 UTC by Danielvandervelden

2023-05-08 07:02 UTC, MichalGorskiOnegini requested changes

2023-05-09 05:03 UTC, pawel-napieracz requested changes

2023-05-09 05:03 UTC, pawel-napieracz commented on tsconfig.json
> +    "target": "ES2018",
is `module` not needed?

2023-05-09 06:30 UTC, Danielvandervelden commented on .storybook/addon/src/components/PanelContent.tsx
> +        const isHexColor = parsedValue.startsWith("#");
Oh good catch! Fixed.

2023-05-09 06:34 UTC, Danielvandervelden commented on package.json
> -    "build": "dts build",
Yes, good catch

2023-05-09 06:35 UTC, Danielvandervelden commented on bundle-analysis.html
Fixed and removed the file entirely from version control

2023-05-09 06:36 UTC, Danielvandervelden commented on src/components/Form/FormGroup/FormGroup.tsx
> +  children: ReactElement[] | ReactElement | string[] | string | number[] | number;
This used to be `ReactChild`, but it's not supported anymore. Most likely we won't need it for string, since pretty much all the time we will wrap that inside a `span` element. I'll remove it from the types defined here.

2023-05-09 06:39 UTC, Danielvandervelden commented on .babelrc.json
> +        }
Fixed

2023-05-09 06:40 UTC, Danielvandervelden commented on package.json
> +    "test": "jest",
I always use `npm test -- --watch` myself indeed. I can add a `test:watch` script in there no problem.

2023-05-09 06:42 UTC, Danielvandervelden commented on src/components/ContextMenu/ContextMenu.test.tsx
> +  it("opens correctly with space, home and end buttons work", async () => {
Yes, but `space` doesn't work nicely in jest tests 😞 . If you change it to space, everything fails...

2023-05-09 06:42 UTC, Danielvandervelden commented on src/components/ContextMenu/ContextMenu.test.tsx
> +    await userEvent.keyboard("{enter}");
Everything fails when u open with `space` instead of `enter`.. But in an actual browser it works.

2023-05-09 06:43 UTC, Danielvandervelden commented on src/components/DataGrid/DataGrid.tsx
> +  const onColumnToggled = (colName: string) => {
Sonar was complaining, and I kind of agreed that it wasn't super necessary. What would we want to change it to in the future? I can't imagine it being anything else than a string :D

2023-05-09 06:44 UTC, Danielvandervelden commented on src/components/DataGrid/DataGridBody/DataGridBody.test.tsx
> +    expect(rows).toHaveLength(4);
I couldn't fix it myself. It was failing, and didn't want to spend even more time fixing this. Maybe we can make a ticket to re-implement this later?

2023-05-09 06:44 UTC, Danielvandervelden commented on src/components/Form/Select/Select.test.tsx
> +    await userEvent.keyboard("{enter}");
See previous comments

2023-05-09 06:45 UTC, Danielvandervelden commented on src/components/Form/Select/SelectService.ts
> +      console.error(
We won't be able to, because the list will never show with options since it doesn't pass this check

2023-05-09 06:48 UTC, Danielvandervelden commented on src/components/Form/Wrapper/SelectWrapper/SelectWrapper.tsx
> +  children: ReactElement[] | string[] | number[];
We would show a list of options. In reality, there should not be only one option in `SelectWrapper`, but you never know what an API returns. I'll add a single ReactElement also.

2023-05-09 06:48 UTC, Danielvandervelden commented on src/components/Notifications/Snackbar/SnackbarProvider/SnackbarProvider.test.tsx
> +    await await userEvent.click(showSuccessSnackbarBtn);
We will be awaiting forever!

Fixed xD

2023-05-09 06:48 UTC, Danielvandervelden commented on src/components/Notifications/Snackbar/SnackbarProvider/SnackbarProvider.test.tsx
> +    await await userEvent.click(showInfoSnackbarBtn);
We will be awaiting forever!

Fixed xD

2023-05-09 06:48 UTC, Danielvandervelden commented on src/components/Notifications/Snackbar/SnackbarProvider/SnackbarProvider.test.tsx
> +    await await userEvent.click(infoSnackbarActions[1]);
We will be awaiting forever!

Fixed xD

2023-05-09 06:48 UTC, Danielvandervelden commented on src/components/Tabs/Tabs.test.tsx
> +    await await userEvent.click(tab3);
We will be awaiting forever!

Fixed xD

2023-05-09 06:48 UTC, Danielvandervelden commented on src/components/Tabs/Tabs.test.tsx
> +    await await userEvent.keyboard("[Space]");
We will be awaiting forever!

Fixed xD

2023-05-09 06:48 UTC, Danielvandervelden commented on src/components/Tabs/Tabs.test.tsx
> +    await await userEvent.keyboard("[End]");
We will be awaiting forever!

Fixed xD

2023-05-09 06:48 UTC, Danielvandervelden commented on src/components/Tabs/Tabs.test.tsx
> +    await await userEvent.keyboard("[Home]");
We will be awaiting forever!

Fixed xD

2023-05-09 06:48 UTC, Danielvandervelden commented on src/components/Tabs/Tabs.test.tsx
> +    await await userEvent.keyboard("a");
We will be awaiting forever!

Fixed xD

2023-05-09 06:49 UTC, Danielvandervelden commented on src/components/Tabs/Tabs.test.tsx
> +    await await userEvent.keyboard("[ArrowRight]");
We will be awaiting forever!

Fixed xD

2023-05-09 06:49 UTC, Danielvandervelden commented on src/components/Tabs/Tabs.test.tsx
> +    await await userEvent.keyboard("[ArrowLeft]");
We will be awaiting forever!

Fixed xD

2023-05-09 06:49 UTC, Danielvandervelden commented on src/components/Tabs/Tabs.test.tsx
> +    await await userEvent.keyboard("[ArrowLeft]");
We will be awaiting forever!

Fixed xD

2023-05-09 06:49 UTC, Danielvandervelden commented on src/hooks/useAnimation.test.tsx
> +    await await userEvent.click(startButton);
We will be awaiting forever!

Fixed xD

2023-05-09 06:49 UTC, Danielvandervelden commented on src/hooks/useBodyClick.test.tsx
> +    await await userEvent.click(button2);
We will be awaiting forever!

Fixed xD

2023-05-09 06:55 UTC, Danielvandervelden commented on stories/DataGrid/DataGrid.stories.tsx
> +  onSort: sort => console.warn(`Sort callback: ${sort}`),
Fixed

2023-05-09 06:58 UTC, Danielvandervelden commented on tsconfig.json
> +    "target": "ES2018",
Nope, the module gets determined in `tsconfig.cjs.json` and `tsconfig.esm.json` for actual builds. The default is `CommonJS` which is fine for development since we have source maps :)

2023-05-09 11:21 UTC, pawel-napieracz requested changes

2023-05-09 11:21 UTC, pawel-napieracz commented on src/components/DataGrid/DataGridBody/DataGridBody.test.tsx
> +    expect(rows).toHaveLength(4);
I fixed it

2023-05-10 05:02 UTC, pawel-napieracz requested changes
Fix  the issue with navigation (see slack DM)

2023-05-10 05:02 UTC, pawel-napieracz requested changes
Fix  the issue with navigation (see slack DM)

2023-05-12 04:49 UTC, pawel-napieracz requested changes
DataGrid and TextElipsis are in wrong places.
usePosition story was removed.
Some stories from DataGrid was removed which was used in docs like pagination.
http://localhost:6006/?path=/docs/components-data-display-typography--docs NOTE does not work anymore, also table on that story and table in BaseStyling

2023-05-16 04:46 UTC, pawel-napieracz commented
I rejected one visual test. Please have a look once you're back

2023-05-24 05:18 UTC, pawel-napieracz approved these changes

2023-05-24 05:18 UTC, merged