UCL-312 - allow checkbox component to have an empty string as a label
onewelcome/react-lib-components pull request #595
Opened 2023-06-01 08:41 UTC by AndreeaIlieThales

Toggle component shows an extra toggle when label text is null or an empty string

2023-06-01 10:15 UTC, MichalGorskiOnegini requested changes

2023-06-01 10:15 UTC, MichalGorskiOnegini commented on src/components/Form/Checkbox/Checkbox.tsx
> +          "You can also pass an empty string, if no label provided"
If you can pass an empty string, doesn't it mean it should be optional then?

2023-06-01 10:15 UTC, MichalGorskiOnegini commented on src/components/Form/Checkbox/Checkbox.tsx
>    const determineLabel = () => {
There is something wrong with this implementation (not yours, but the entire implementation)

I am trying to understand why the supposed method to 'determine' a label is returning a label OR children. Some initial decisions did not work in the end, but instead of taking a step back, we need to create a bunch of conditional to satisfy that requirement. 

I'm sure there is some explanation for why it was done like this, but I would strongly opt to have it reworked a little, so the label is label and children are children. For now, there is no example of how to do it from my side, but what is your opinion? Do you think we should do it now? Next ticket? Or am I picky?

2023-06-01 11:38 UTC, AndreeaIlieThales commented on src/components/Form/Checkbox/Checkbox.tsx
>    const determineLabel = () => {
I agree and maybe i didn't do the right decision here, I should have discussed it with you guys first and figured out why we need this implementation in the first place. Normally, I do agree with you, label and children should be separate, but I feel like I am missing a little bit of context. @Danielvandervelden and @pawel-napieracz could you guys help out on this?

2023-06-12 08:55 UTC, Danielvandervelden requested changes

2023-06-12 08:55 UTC, Danielvandervelden commented on src/components/DataGrid/DataGridActions/DataGridColumnsToggle.tsx
> +    ></Toggle>
Can be auto closed

```suggestion
    />
```

2023-06-12 08:55 UTC, Danielvandervelden commented on src/components/Form/Checkbox/Checkbox.tsx
>    const determineLabel = () => {
Back when we created the Checkbox component, there were different things you can pass as a child. We used `ReactNode` as a type for `children` prop, which can be many different things. Because you can basically ruin the entire checkbox styling I scoped this to be either a `span` or a `string`. If it were anything other, we would throw an error. It was a sort of "guard clause" I guess in order to make sure people used the library correctly.

However, if we don't want to protect against this we can simply return whatever is assigned to `children` (or now `label` prop). All though I don't entirely understand why we opted to go with a `label` prop instead of just using `children`? @AndreeaIlieThales  @MichalGorskiOnegini

2023-06-12 08:55 UTC, Danielvandervelden commented on src/components/Form/Toggle/Toggle.test.tsx
> +    const { toggle } = createToggle(undefined);
Passing `undefined` shouldn't be necessary, right? 🤔

2023-06-12 08:55 UTC, Danielvandervelden commented on src/components/Form/Toggle/Toggle.tsx
> +  children?: ReactNode;
Can remove `children` here, as well as in the omitted `props`. Then in `Checkbox.tsx` remove the `children` definition in the Props interface.

2023-06-12 08:55 UTC, Danielvandervelden commented on stories/Form/Elements/Checkbox.mdx
> +<ArgTypes story="{PRIMARY_STORY}" />
Why is it surrounded with quotes?

2023-06-13 05:53 UTC, AndreeaIlieThales commented on src/components/Form/Toggle/Toggle.test.tsx
> +    const { toggle } = createToggle(undefined);
yes, that's a leftover

2023-06-13 05:57 UTC, MichalGorskiOnegini commented on src/components/Form/Checkbox/Checkbox.tsx
>    const determineLabel = () => {
Not sure if this answers the question, but when reviewing the code, it seemed super confusing to me with all the checks that we did. To keep things simple and easier to update in the future, I opted for such a change.

2023-06-14 07:31 UTC, Danielvandervelden submitted a review, later dismissed

2023-06-14 10:59 UTC, MichalGorskiOnegini approved these changes

2023-06-14 10:59 UTC, merged