UCL-287 - add interactions to stories where necessary
onewelcome/react-lib-components pull request #619
Opened 2023-07-27 14:44 UTC by Danielvandervelden

2023-08-07 14:12 UTC, MichalGorskiOnegini requested changes

2023-08-07 14:12 UTC, MichalGorskiOnegini commented on src/components/Popover/Popover.tsx
> +  useEffect(() => {
Shouldn't both useEffects be merged?

2023-08-07 14:12 UTC, MichalGorskiOnegini commented on src/components/Popover/Popover.tsx
> +  }, [show]);
What is the difference between `show` and `showPopover`?

2023-08-07 14:12 UTC, MichalGorskiOnegini commented on src/hooks/usePosition.ts
> +      setInitialCalculationDone(true);
Why are we adding this?

2023-08-08 07:26 UTC, Danielvandervelden commented on src/hooks/usePosition.ts
> +      setInitialCalculationDone(true);
Because otherwise the popup shows itselfs and then suddenly it hops to the correct position. So in order to not have it blink from one place to another we wait until initial calculations are done.

2023-08-08 07:29 UTC, Danielvandervelden commented on src/components/Popover/Popover.tsx
> +  }, [show]);
This is a fix that we do to make sure that we only show the popover when the initial calculation is done (see comment on why we have 2 show properties).

2023-08-08 07:29 UTC, Danielvandervelden commented on src/components/Popover/Popover.tsx
> +  useEffect(() => {
Yes, good point. Fixed

2023-08-16 04:55 UTC, MichalGorskiOnegini approved these changes

2023-08-16 04:55 UTC, merged