UCL-351 updated Toggle to Quantum design
onewelcome/react-lib-components pull request #622
Opened 2023-07-28 14:00 UTC by Danielvandervelden

2023-08-02 11:25 UTC, pawel-napieracz approved these changes

2023-08-11 12:31 UTC, MichalGorskiOnegini requested changes

2023-08-11 12:31 UTC, MichalGorskiOnegini commented on stories/Form/Elements/Toggle.stories.tsx
> +const Template: Story<Props> = args => {
```suggestion
const Template: StoryFn<Props> = args => {
```

apparently, Story is deprecated

2023-08-11 12:31 UTC, MichalGorskiOnegini commented on stories/Form/Elements/Toggle.stories.tsx
>  export const Toggle = Template.bind({});
It cannot be checked. Same goes for the `Docs` example (not sure if that's the same one)

2023-08-11 14:03 UTC, MichalGorskiOnegini approved these changes

2023-08-11 14:08 UTC, merged