UCL-324 Tabs uses Quantum stylings and behaviour
onewelcome/react-lib-components pull request #634
Opened 2023-09-22 09:39 UTC by pawel-napieracz

2023-09-26 09:34 UTC, pawel-napieracz commented
I changed `buttonBorderRadius` so maybe that's why there are so many changes to so many stories ;)

2023-10-02 13:09 UTC, MichalGorskiOnegini requested changes

2023-10-04 09:43 UTC, pawel-napieracz commented on src/components/Tabs/Tab.tsx
I don't think we should support that, as we don't have a requirement to have sub-level navigation

2023-10-04 09:49 UTC, pawel-napieracz commented on src/components/Tabs/Tab.tsx
Have the same: 
<img width="344" alt="Screenshot 2023-10-04 at 11 49 00" src="https://github.com/onewelcome/react-lib-components/assets/41371371/20a9b0e7-0aaa-4f74-a105-0bc04ee438ea">
<img width="1128" alt="Screenshot 2023-10-04 at 11 49 12" src="https://github.com/onewelcome/react-lib-components/assets/41371371/0ac6e107-c003-4a53-8122-c89407015a07">

2023-10-04 09:52 UTC, pawel-napieracz commented on src/components/Tabs/TabButton.tsx
> +  const tabButtonClasses = [classes["tabbutton"]];
You mean 
```
const tabButtonClasses = [];
tabButtonClasses.push(classes["tabbutton"])
```
?
If you want we can add it ;)

2023-10-04 14:51 UTC, MichalGorskiOnegini commented on src/components/Tabs/Tab.tsx
https://63e21de9a62cab5a8a3e31c7-kudmomstcz.chromatic.com/?path=/story/components-navigation-tabs--tabs-with-icons

2023-10-04 14:52 UTC, MichalGorskiOnegini commented on src/components/Tabs/Tab.tsx
I mean ACTIVE state on the focus-visible.

2023-10-05 04:50 UTC, pawel-napieracz commented on src/components/Tabs/Tab.tsx
Validated with design and previously with Clement. It has the same properties, but the browser renders it slightly differently.

2023-10-05 04:51 UTC, pawel-napieracz commented on src/components/Tabs/Tab.tsx
Can you verify it? 
https://www.figma.com/file/zAzyG3fmBFKrdrVzFeEYAv/Quantum---2.-%F0%9F%8C%9E-Light-Components?node-id=16674%3A481731&mode=dev
https://63e21de9a62cab5a8a3e31c7-kudmomstcz.chromatic.com/?path=/story/components-navigation-tabs--tabs-with-icons

2023-10-05 04:53 UTC, pawel-napieracz commented on src/components/Tabs/Tab.tsx
🧔‍♂️, I still see that those are aligned

2023-10-05 05:55 UTC, MichalGorskiOnegini commented on src/components/Tabs/Tab.tsx
looks good :)

2023-10-05 09:42 UTC, MichalGorskiOnegini approved these changes

2023-10-05 09:42 UTC, merged