UCL-410 Make id property optional and generate if empty
onewelcome/react-lib-components pull request #663
Opened 2023-12-29 11:00 UTC by MichalGorskiOnegini

2024-01-02 08:58 UTC, Danielvandervelden requested changes

2024-01-02 08:58 UTC, Danielvandervelden commented on src/components/ContextMenu/ContextMenu.tsx
> +import * as crypto from "crypto";
Using `crypto` NodeJS package will mess projects up that are using our component library. Frontend projects do not have this, and webpack does not provide polyfills for this either so that means we need to add a dependency that polyfills this module. 

Luckily, we have a beautiful `generateID` function inside `util/helper.tsx`. Please use this to generate an arbitrary id to be used 🙂

2024-01-09 10:48 UTC, MichalGorskiOnegini commented on src/components/ContextMenu/ContextMenu.tsx
> +import * as crypto from "crypto";
that's a very fair argument. Thanks!

2024-01-11 10:34 UTC, Danielvandervelden approved these changes

2024-01-11 10:34 UTC, merged