UCL-436 rename Snackbar to Alert
onewelcome/react-lib-components pull request #673
Opened 2024-03-01 06:07 UTC by akosszeredai

This is a member of:
https://onewelcome.atlassian.net/browse/UCL-356

2024-03-05 10:51 UTC, pawel-napieracz requested changes

2024-03-05 10:51 UTC, pawel-napieracz commented on src/components/Notifications/Alert/AlertItem/AlertItem.tsx
> +        <div className={classes["content-wrapper"]} role="log">
no need for `role='log'` https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/log_role

2024-03-05 10:51 UTC, pawel-napieracz commented on src/components/Notifications/Alert/AlertItem/AlertItem.tsx
> +      role="alert"
I'd remove `role='alert'`.

Setting role="alert" is equivalent to setting [aria-live="assertive"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live) and [aria-atomic="true"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-atomic)

2024-03-05 10:51 UTC, pawel-napieracz commented on src/components/Notifications/Alert/AlertItem/AlertItem.tsx
> +          {!!title && !!content && (
please bring back renderTitle

2024-03-05 10:51 UTC, pawel-napieracz commented on src/components/Notifications/Alert/AlertItem/AlertItem.tsx
> +          {(!!content || !!title) && (
please bring back `renderContentOrTitleOnly`

2024-03-05 10:51 UTC, pawel-napieracz commented on src/components/Notifications/Alert/AlertItem/AlertItem.tsx
> +              {content || title}
I'd bring back `hasOnlyTitle`.

2024-03-05 10:51 UTC, pawel-napieracz commented on src/components/Notifications/Alert/AlertItem/AlertItem.tsx
> +      onBlur={onItemBlur}
good catch!

2024-03-05 10:51 UTC, pawel-napieracz commented on src/components/Notifications/Alert/AlertProvider/AlertProvider.tsx
> +export type PropsOrTitle = EnqueueAlertProps | string | undefined;
Move it to interfaces file.

2024-03-05 10:51 UTC, pawel-napieracz commented on src/components/Notifications/NotificationProvider/NotificationContext.test.tsx
> +    <AlertProvider closeButtonTitle="close" key={5}>
key is useless

2024-03-05 11:44 UTC, pawel-napieracz requested changes

2024-03-05 11:44 UTC, pawel-napieracz commented on src/components/Notifications/Alert/useAlert.ts
> +    enqueueWarningAlert: ctx.enqueueWarningAlert,
please keep backward compatibility

2024-03-05 11:44 UTC, pawel-napieracz commented on src/index.ts
> +export type { Props as AlertProviderProps } from "./components/Notifications/Alert/AlertProvider/AlertProvider";
please keep backward compatibility

2024-03-05 11:44 UTC, pawel-napieracz commented on src/index.ts
> +export { useAlert } from "./components/Notifications/Alert/useAlert";
please keep backward compatibility

2024-03-11 10:04 UTC, akosszeredai commented on src/components/Notifications/Alert/AlertItem/AlertItem.tsx
> +        <div className={classes["content-wrapper"]} role="log">
Removed in the visuals branch.

2024-03-11 10:05 UTC, akosszeredai commented on src/components/Notifications/Alert/AlertItem/AlertItem.tsx
> +      role="alert"
Default is polite. Error medium and high emphasis gets the assertive.

2024-03-11 10:06 UTC, akosszeredai commented on src/components/Notifications/Alert/AlertItem/AlertItem.tsx
> +          {!!title && !!content && (
Reason?

2024-03-11 10:06 UTC, akosszeredai commented on src/components/Notifications/Alert/AlertItem/AlertItem.tsx
> +      onBlur={onItemBlur}
Ty

2024-03-11 12:21 UTC, closed without merging