UCL-453 | Quantumize FileUpload component
onewelcome/react-lib-components pull request #695
Opened 2024-05-09 09:40 UTC by ambujThalesOW

#### Ticket :  https://onewelcome.atlassian.net/browse/UCL-453

### Description
Re-wamp File Upload component as per latest [Figma](https://www.figma.com/file/KbnKALNEy8aQThvcuZt61K/OneWelcome-components?type=design&node-id=870-2&mode=design&t=bkABj5Arqrj2xPw1-0)

2024-05-10 09:29 UTC, pawel-napieracz requested changes

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +    return actionIconsSet;
```
    return actionIcons.map(icon => 
        <Icon
          key={icon.action}
          title={icon.action}
          icon={icon.type}
          className={classes["action-icon"]}
          onClick={() => onRequestedFileAction.?(icons.action, name) }
        >
          {icons.action !== FILE_ACTION.DOWNLOAD && (
            <label>{icon.action !== FILE_ACTION.ABORT ? icon.action : ""}</label>
          )}
          {icons.action === FILE_ACTION.DOWNLOAD && (
            <a href={downloadFileLink} target="_blank" rel="noreferrer">
              {icon.action}
            </a>
          )}
        </Icon>
  );
```

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +            <a href={downloadFileLink} target="_blank" rel="noreferrer">
what if downloadFileLink is empty? `a` tag is not needed then (remember about CSS prop to set cursor on icon element if not set)

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +            )}
looks as something we can extract to method or component :)

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +        <div className={`${status && status === UPLOADING ? classes["progress-with-action"] : ""}`}>
don't need to check for status. status === UPLOADING should be enought

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +              percentage={40}
why these percentage and completness number :O?

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +          )}
to avoid that let's go with {status === UPLOADING && <Component />}

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +  const renderActionIcon = (
`renderActionIcons`

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +            )}
isn't that status==retry part of actionIcons?

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +            {icons.actionIcon && renderActionIcon(icons.actionIcon, status)}
maybe move check for `icons.actionIcon` inside `renderActionIcon`?

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.module.scss
> +    border: 1px dashed var(--color-blue-grey100);
move border to variable. We already have `var(--input-border-width)`, maybe we can reuse it if it matches?

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.module.scss
> +    border: 1px dashed var(--color-blue-grey100);
also `dashed` can be moved to some variable? But not necessary. Do what you think.

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +        console.error("incorrect file format. Allowed format are", accept);
please talk with @Clement who we ca show that.
Maybe we should give possibility to pass callback method which we can call there?

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +            {title} <span className={classes["file-upload-title-mandatory"]}>*</span>
I guess we need `*` only when `required` prop is set, right?

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +          {fileList?.length > 0 && (
no need to `?` if it's required prop

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +                <li key={name} className={"completed"} id={name}>
remove global classes

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +                    {...rest}
```suggestion
                    {...rest}
                    className={`${classes["upload-input"]` ${rest.className}}}
```

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +                    {...(multiple && { multiple: true })}
it's very confusing for me. Can't we just do `multiple={multiple ?? true}` if we want to have multiple default to true? Or set `true` when getting proper for that component to make it default.

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +                    spellCheck={rest.spellCheck ?? false}
can be always set to false IMO

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Icon/Icon.module.scss
> +}
is it really the same icon?

2024-05-10 09:29 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.module.scss
> +    border: 1px dashed var(--color-blue-grey100);
`var(--drag-border-style)` -> you have that one

2024-05-10 09:29 UTC, pawel-napieracz commented on src/mixins.module.scss
> +    }
that mixin is used in a lot of places. PLease put that code in your component's stylesheet

2024-05-10 11:18 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileItem/FileItem.module.scss
> +      flex-wrap: nowrap;
Yes, you are right but sometimes it's good to define so it won't override by another `class/id`. I removed here for now

2024-05-10 12:03 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileUpload.tsx
> +            {title} <span className={classes["file-upload-title-mandatory"]}>*</span>
isn't `title` already mandatory?
<img width="575" alt="Screenshot 2024-05-10 at 5 32 26 PM" src="https://github.com/onewelcome/react-lib-components/assets/129168707/6aa3505b-06f3-409a-ae8b-ac8c8ac26277">

2024-05-10 12:09 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileUpload.tsx
> +          {fileList?.length > 0 && (
Again not added by me but it's good to have as a safety hook because we are not sure how people may handle it after integration and if any case for any reason fileList come as empty/null then it may break execution. what is your thought?

2024-05-10 12:28 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileUpload.tsx
> +                    {...(multiple && { multiple: true })}
legacy code but yes suggested way should work also

2024-05-13 03:42 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileItem/FileItem.module.scss
> +        span[class*="bar--"],
I didn't...It was already present and I simply added `bar2--` as it's height was not matching with `bar1--`. it looks miss to me with actual progress bar. Also, I don't think so it's auto generated or changeable as it's for blue strip (progress) but i completely got your point. Let's discuss if yet not clear or convinced

2024-05-13 03:48 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +            )}
Yes, it's part of actionIcons but here INFO icon is appending which is specifically visible for Retry case only.
![image](https://github.com/onewelcome/react-lib-components/assets/129168707/ae46c771-8c88-41b2-a3f8-f24ef15ae970)

2024-05-13 03:51 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +            {icons.actionIcon && renderActionIcon(icons.actionIcon, status)}
isn't better to check outside function so it will save functional call if required info/params are not available?

2024-05-13 04:31 UTC, ambujThalesOW commented on src/components/Typography/Typography.module.scss
> +      0.25rem
for now I have independently manage this change for File upload only and same as early for all other places but Yes this concern should raise & discuss with UX team to avoid further non-consistency

2024-05-15 06:53 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileUpload.tsx
> +        console.error("incorrect file format. Allowed format are", accept);
Discussed with Clement and it will be represent like below
![image](https://github.com/onewelcome/react-lib-components/assets/129168707/f1a9f197-1cd8-4988-abd9-7acd638865d0)

2024-05-15 06:54 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +            {icons.actionIcon && renderActionIcon(icons.actionIcon, status)}
as discussed, i am keeping it same

2024-05-15 06:56 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +              percentage={40}
it was miss from my end for manual testing purpose

2024-05-15 07:17 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +            <a href={downloadFileLink} target="_blank" rel="noreferrer">
`downloadFileLink` is not available then `Download` button won't appear

2024-05-15 07:20 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +    return actionIconsSet;
No more applicable as I changed this area and using UCL button & Link component to render action button

2024-05-15 07:20 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileItem/FileItem.tsx
> +      case UPLOADING:
`enum` added for all status and using it

2024-05-15 07:22 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileItem/FileItem.module.scss
> +        span[class*="bar--"],
As discussed, I have removed desired change and targeting element by tag  but there are more legacy instance available which need to fix by creating separate ticket for same

2024-05-15 08:37 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +            {title} <span className={classes["file-upload-title-mandatory"]}>*</span>
it's not about the title. It's about uploading the file. It might be optional to upload anything, for example we can have form where you can upload logo, but if you don't default will be used. In that case fileuplaod should not be mandatory ;)

2024-05-15 09:27 UTC, pawel-napieracz requested changes

2024-05-15 09:27 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +        setErrorMsg(`Invalid file format. Supported formats are: ${accept}.`);
We need translation for that. Please check how we deal with that for example in `DataGridColumnsToggle.tsx`

2024-05-15 09:27 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +      errorTextClass.push(classes["error"]));
that is so complex 🙈 . Please split it into more assignments like this:
```
(inputError || error || errorMsg) && dropzoneClassNames.push(classes["error"]) && subTextClass.push(classes["error"])
errorMsg && errorTextClass.push(classes["error"]));
```

2024-05-15 09:27 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +    console.log("inside handleOnDrop", e);
:)

2024-05-15 09:27 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +                <li key={name} className={status} id={name}>
- still you are using global class, not by `classes[status]`. What is the reason for it? 
- do you need id?

2024-05-15 09:27 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +                    multiple={multiple ?? true}
just multiple is enough

2024-05-15 09:27 UTC, pawel-napieracz commented on src/components/_BaseStyling_/BaseStyling.tsx
> +    defaultUnit1px: "1px",
you dont use it, dont u?

2024-05-15 10:16 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileUpload.tsx
> +                <li key={name} className={status} id={name}>
This is how it was written so I didn't change

2024-05-16 08:56 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.tsx
> +                <li key={name} className={status} id={name}>
Ok, we can keep it that way.

2024-06-03 06:48 UTC, pawel-napieracz commented on src/components/_BaseStyling_/BaseStyling.tsx
> +  defaultZIndex1?: string;
Sorry for confusion but I was refering to other `z-index` we have, see: https://github.com/onewelcome/react-lib-components/blob/594d8995fcba1bde3c95b542ee8c8531662451d9/src/variables.scss#L22
This is for easier check what if above what :)

2024-06-03 10:25 UTC, pawel-napieracz approved these changes

2024-06-03 10:36 UTC, merged