UCL-451 Update storybook from V7 to V8
onewelcome/react-lib-components pull request #697
Opened 2024-05-14 11:37 UTC by MichalGorskiOnegini

2024-05-27 13:14 UTC, szmejk requested changes

2024-05-27 13:14 UTC, szmejk commented on stories/Form/Elements/MultiSelect.stories.tsx
> +import { userEvent, waitFor, within, expect } from "@storybook/test";
see above, over here this new utilty package is used

2024-05-27 13:14 UTC, szmejk commented on stories/Typography/Typography.stories.tsx
> +      diffThreshold: 0.9 //To not look at font change, checked with https://6262c53f521620003ac2ff49-ukmsdlppcb.chromatic.com/?path=/story/stories-diff-threshold-check--test-yours-out
nice!

2024-06-05 14:22 UTC, MichalGorskiOnegini commented on stories/Typography/Typography.stories.tsx
> +      diffThreshold: 0.9 //To not look at font change, checked with https://6262c53f521620003ac2ff49-ukmsdlppcb.chromatic.com/?path=/story/stories-diff-threshold-check--test-yours-out
kudos to @pawel-napieracz :D

2024-06-05 15:08 UTC, MichalGorskiOnegini commented on CONTRIBUTING.md
> -    "import { Story, Canvas, Title, Subtitle, ArgsTable, PRIMARY_STORY } from '@storybook/addon-docs';",
good catch

2024-06-05 15:10 UTC, MichalGorskiOnegini commented on src/components/Tiles/Tile.test.tsx
> +import { waitFor } from "@testing-library/dom";
it's not a storybook test :D

2024-06-11 08:33 UTC, szmejk commented on src/components/Tiles/Tile.test.tsx
> +import { waitFor } from "@testing-library/dom";
:see_no_evil:

2024-06-11 12:49 UTC, szmejk approved these changes

2024-06-14 06:27 UTC, szmejk approved these changes

2024-06-14 06:28 UTC, merged