AE-768 | ContentHeader collapse hook created
onewelcome/react-lib-components pull request #714
Opened 2024-06-28 07:47 UTC by Shubhamkumar2023

- New hook created for the collapse purpose
- Expose hook outside
- Ct added

2024-06-28 10:56 UTC, MichalGorskiOnegini requested changes

2024-06-28 10:56 UTC, MichalGorskiOnegini commented on src/hooks/useContentHeaderCollapse.test.ts
> +describe("we should get the correct return values", () => {
```suggestion
describe("useContentHeaderCollapse", () => {
```

2024-06-28 10:56 UTC, MichalGorskiOnegini commented on stories/FormWithStepper/FormWithStepper.stories.tsx
> +const Template1: StoryFn<Props> = args => {
```suggestion
const TemplateWithScroll: StoryFn<Props> = args => {
```

or something similar

2024-06-28 10:56 UTC, MichalGorskiOnegini commented on stories/FormWithStepper/FormWithStepper.stories.tsx
Can you also mention a goal of the hook somewhere in the storybook?

2024-06-29 04:01 UTC, Shubhamkumar2023 commented on stories/FormWithStepper/FormWithStepper.stories.tsx
> +const Template1: StoryFn<Props> = args => {
Removed and created new story for hook

2024-06-29 04:02 UTC, Shubhamkumar2023 commented on stories/FormWithStepper/FormWithStepper.stories.tsx
I have created a separate story for the hook. 
![image](https://github.com/onewelcome/react-lib-components/assets/126144731/37659ab6-0f14-403d-97f1-8e063757c4fb)

2024-07-02 09:42 UTC, MichalGorskiOnegini approved these changes

2024-07-02 09:44 UTC, merged