UCL-496 DataGrid filters enhancements
onewelcome/react-lib-components pull request #722
Opened 2024-07-19 10:53 UTC by szmejk

2024-07-24 11:53 UTC, MichalGorskiOnegini requested changes

2024-07-24 11:53 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridFilters/DataGridFilterTag.tsx
> +    <div {...rest} ref={ref} className={classes["filter-wrapper"]}>
In this file, line :42 there is hardcoded 'other'

2024-07-24 11:53 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridFilters/DataGridFilterTag.tsx
> +        ref={triggerRef}
It may not be the correct code but as discussed on Slack, remember about the tag button hover to highlight entire oval element.

2024-07-24 11:53 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridFilters/DataGridFilterTag.tsx
>    const shouldRenderEditTag = mode === "EDIT" && filter;
line :60 there is a weird looking newline

2024-07-24 11:53 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridFilters/DataGridFilterTag.tsx
>          {shouldRenderAddTag && (
random place for a reminder: we should change the sorting icons to arrows

2024-07-24 11:53 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridFilters/DataGridFilter.tsx
>            values={values}
yen another random place for a comment:

please, do not give up on: `maybe extract the filters reducer to a separate hook`

2024-08-13 14:15 UTC, szmejk commented on src/components/DataGrid/DataGridFilters/DataGridFilterTag.tsx
> +        ref={triggerRef}
done

2024-08-13 14:15 UTC, szmejk commented on src/components/DataGrid/DataGridFilters/DataGridFilterTag.tsx
>          {shouldRenderAddTag && (
done

2024-08-13 14:15 UTC, szmejk commented on src/components/DataGrid/DataGridFilters/DataGridFilter.tsx
>            values={values}
done

2024-08-21 10:35 UTC, MichalGorskiOnegini approved these changes

2024-08-21 10:45 UTC, merged