UCL-537 DataGrid nested rows
onewelcome/react-lib-components pull request #734
Opened 2024-09-20 18:38 UTC by szmejk

2024-09-26 13:23 UTC, MichalGorskiOnegini requested changes

2024-09-26 13:23 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridBody/DataGridRow/DataGridRow.module.scss
> +      background-color: var(--light-grey-border);
as discussed, the color should (most likley) be sligthly different :D

2024-09-26 13:23 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridBody/DataGridRow/DataGridRow.tsx
> +  enableNestedRow?: boolean;
shouldn't we combine nested rows related properties to a single object?

2024-09-26 13:23 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridBody/DataGridRow/DataGridRow.tsx
> +  const renderRecurrentRow = () => {
Is `recurrent` what you really meant?

2024-09-26 13:23 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridBody/DataGridRow/DataGridRow.tsx
> +    const nestedChildOffset = !hasNestedChildren ? 46 : 0;
The cognitive load here is quite high. The minimum solution I could suggest is to extract those 'random' numbers to some constant that gives at least minimal explanation on what it is. If you introduce a hook as stated before, you could also extract it to some function e.g `calculateIndentation`.

2024-09-26 13:23 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGrid.test.tsx
> +    expect(getByText("Company 3")).toBeInTheDocument();
You should also check if its not available before you clicked on the expand row button.

2024-09-26 13:23 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGrid.test.tsx
> +describe("DataGrid with nested rows", () => {
Perhaps we should move it to a separate testing file? Not pushing for that but I'm worried how quickly this file grows...

2024-09-26 13:23 UTC, MichalGorskiOnegini commented on stories/DataGrid/DataGrid.stories.tsx
> +            <DataGridRow key={item.id}>
I'm getting lost here a bit. So to enable nested rows you need to pass the key under which you can find a nested element. That is fine, however, in DataGridRow we have enableNestedRow property that can be used as well. Is it by design, so you can turn it off for a specific row?

2024-09-30 15:19 UTC, szmejk commented on src/components/DataGrid/DataGridHeader/DataGridHeader.tsx
> +        {/* <td style={{ paddingRight: spacing?.paddingRight, width: "1px" }}></td>
removed

2024-09-30 15:19 UTC, szmejk commented on stories/DataGrid/DataGrid.stories.tsx
> +      id: "3",
that warning was actually unrelated to the item id, but rather had to do with me not passing any key to the connector components

2024-09-30 15:19 UTC, szmejk commented on src/components/DataGrid/DataGridBody/DataGridRow/DataGridRow.tsx
> +  const renderNestedRowConnectors = () => {
done

2024-09-30 15:19 UTC, szmejk commented on src/components/DataGrid/DataGridBody/DataGridRow/DataGridRow.module.scss
> +      background-color: var(--light-grey-border);
done

2024-09-30 15:19 UTC, szmejk commented on src/components/DataGrid/DataGridBody/DataGridRow/DataGridRow.tsx
> +  enableNestedRow?: boolean;
done

2024-09-30 15:19 UTC, szmejk commented on src/components/DataGrid/DataGridBody/DataGridRow/DataGridRow.tsx
> +  const renderRecurrentRow = () => {
changed to `nested`

2024-09-30 15:20 UTC, szmejk commented on src/components/DataGrid/DataGridBody/DataGridRow/DataGridRow.tsx
> +    const nestedChildOffset = !hasNestedChildren ? 46 : 0;
done

2024-09-30 15:20 UTC, szmejk commented on src/components/DataGrid/DataGrid.test.tsx
> +    expect(getByText("Company 3")).toBeInTheDocument();
done

2024-09-30 15:21 UTC, szmejk commented on stories/DataGrid/DataGrid.stories.tsx
> +            <DataGridRow key={item.id}>
the `enableNestedRow` is just an internal prop and it's based on the key

2024-10-01 11:01 UTC, MichalGorskiOnegini approved these changes

2024-10-01 11:06 UTC, merged