UCL-550 Added disableAddNew to collumn metadata, updated storybook
onewelcome/react-lib-components pull request #735
Opened 2024-09-24 12:02 UTC by lubos-tomsa

2024-09-25 11:55 UTC, lubos-tomsa commented
Note that Snyk failures are fixed in UCL-332 so it's possible to ignore them in this PR.

2024-09-30 07:24 UTC, szmejk requested changes

2024-09-30 07:24 UTC, szmejk commented on src/components/DataGrid/DataGridFilters/DataGridToolbar.test.tsx
> +  fdescribe("'Create new' button enabled/disabled feature", () => {
should probably be `describe`

2024-09-30 07:24 UTC, szmejk commented on src/components/DataGrid/DataGridFilters/DataGridToolbar.test.tsx
> +      expect(() => getByText("create new", { exact: false })).toThrow();
There's a more standard way of testing [if elements are not present in RTL](https://testing-library.com/docs/guide-disappearance/#asserting-elements-are-not-present). Could you please check it out?

2024-09-30 11:17 UTC, lubos-tomsa commented on src/components/DataGrid/DataGridFilters/DataGridToolbar.test.tsx
> +  fdescribe("'Create new' button enabled/disabled feature", () => {
fixed; yes, this was a forgotten focused describe, I was used to use these & to have a linter rule not to forget it :D

2024-09-30 11:18 UTC, lubos-tomsa commented on src/components/DataGrid/DataGridFilters/DataGridToolbar.test.tsx
> +      expect(() => getByText("create new", { exact: false })).toThrow();
fixed, thanks, I thought there should be a better option

2024-10-01 07:25 UTC, szmejk approved these changes

2024-10-01 07:29 UTC, merged