UCL-524 Add Calendar component
onewelcome/react-lib-components pull request #736
Opened 2024-09-30 11:01 UTC by MichalGorskiOnegini

2024-10-01 10:02 UTC, pawel-napieracz requested changes

2024-10-01 10:02 UTC, pawel-napieracz commented on stories/DatePicker/DatePicker.stories.tsx
> +  await waitFor(() => expect(dayOfTheMonth).toBeDefined);
is waitFor needed? because in current code it was always something as you are checking if toBeDefined returns method reference
 
```suggestion
  await waitFor(() => expect(dayOfTheMonth).toBeDefined());
  or 
  await expect(dayOfTheMonth).toBeDefined();
  ???
```

2024-10-01 10:04 UTC, pawel-napieracz commented on src/components/DatePicker/DatePicker.tsx
> +      {...rest}
now, we allow to override classNames. Do we really want that? Maybe we should rethink order?

2024-10-01 10:10 UTC, pawel-napieracz commented on src/components/DatePicker/DatePicker.module.scss
> +/*
Ok, I got it. Currently we support only single select

2024-10-01 13:51 UTC, MichalGorskiOnegini commented on src/components/DatePicker/DatePicker.module.scss
> +  cursor: pointer;
can you elaborate? :/

2024-10-01 14:00 UTC, MichalGorskiOnegini commented on src/components/DatePicker/DatePicker.tsx
> +      weekStartsOn={1}
I'll ask @cjourdai

2024-10-01 14:06 UTC, MichalGorskiOnegini commented on src/components/DatePicker/DatePicker.tsx
> +      required={true}
you are right

2024-10-01 14:12 UTC, MichalGorskiOnegini commented on src/components/DatePicker/DatePicker.tsx
> +export interface Props {
went with onSelect

2024-10-01 14:16 UTC, MichalGorskiOnegini commented on src/components/DatePicker/DatePicker.tsx
> +export const DatePicker: ForwardRefRenderFunction<HTMLDivElement, Props> = ({
lets discuss tomorrow, I think I misunderstood something.

2024-10-01 14:21 UTC, MichalGorskiOnegini commented on src/components/Typography/Typography.tsx
> +const TypographyComponent: ForwardRefRenderFunction<any, Omit<Props, "ref">> = (
it started failing to me locally, so I've adjusted the type a little bit

2024-10-01 14:23 UTC, MichalGorskiOnegini commented on package.json
> +    "react-day-picker": "^9.1.3",
lets discuss

2024-10-01 14:27 UTC, MichalGorskiOnegini commented on src/components/DatePicker/DatePicker.tsx
> +export interface Props {
lets discuss

2024-10-01 14:28 UTC, MichalGorskiOnegini commented on stories/DatePicker/DatePicker.stories.tsx
> +  });
To me its more readable this way. It also 'tests' that the data-testid can be easily passed.

2024-10-01 14:30 UTC, MichalGorskiOnegini commented on stories/DatePicker/DatePicker.stories.tsx
> +  await waitFor(() => expect(dayOfTheMonth).toBeDefined);
the current code has a. bug indeed. IMO this is required. I've spent too much time already on flaky tests :D

2024-10-02 08:55 UTC, MichalGorskiOnegini commented on src/components/DatePicker/DatePicker.module.scss
> +  cursor: pointer;
discussed offline

2024-10-04 06:27 UTC, pawel-napieracz requested changes

2024-10-04 06:27 UTC, pawel-napieracz commented on src/components/Button/BaseButton.module.scss
> +
can you help me understand it offline?

2024-10-04 06:27 UTC, pawel-napieracz commented on package.json
> +    "react-day-picker": "^9.1.3"
maybe it's not needed? If it's please put it in devDependency :)

2024-10-04 06:27 UTC, pawel-napieracz commented on src/components/DatePicker/DatePicker.module.scss
> +  }
we have mixin for this

2024-10-04 06:27 UTC, pawel-napieracz commented on src/components/DatePicker/DatePicker.module.scss
> +  }
we have mixin for this

2024-10-04 06:27 UTC, pawel-napieracz commented on src/components/DatePicker/DatePicker.module.scss
> +  }
we have mixin for this :)

2024-10-04 06:27 UTC, pawel-napieracz commented on src/components/DatePicker/DatePicker.module.scss
> +    border-radius: 2px;
`var(--focus-border-radius)`?

2024-10-04 06:27 UTC, pawel-napieracz commented on src/components/Form/FileUpload/FileUpload.module.scss
> +  }
can't we just do:
```suggestion
    @include transition(all, 0.2s, ease-in-out);
```
It will be less confusing IMO

2024-10-04 06:27 UTC, pawel-napieracz commented on src/components/Form/Input/Input.module.scss
> +  }
same

2024-10-04 06:27 UTC, pawel-napieracz commented on stories/DatePicker/DatePicker.mdx
> +      <DatePicker value={inputValue} onSelect={setInputValue} locale="enGB"></DatePicker>
one remark. Can we somehow provide a locale in standardized way? So I'm assuming we can provide `en_GB` :P

2024-10-04 06:49 UTC, pawel-napieracz commented on src/components/Button/BaseButton.module.scss
> +
thanks. New semantic. We will apply it everywhere :)

2024-10-04 08:17 UTC, merged