UCL 552 Allow DataGrid consumers to easily map values to keys to filter data with keys/IDs
onewelcome/react-lib-components pull request #739
Opened 2024-10-09 13:32 UTC by lubos-tomsa

2024-10-17 07:25 UTC, szmejk approved these changes

2024-10-17 07:28 UTC, szmejk requested changes

2024-10-17 07:28 UTC, szmejk commented on src/components/DataGrid/DataGridFilters/FilterKeyMapper.test.ts
> +    it("should provide values", () => {
should provide keys for values?

2024-10-17 07:28 UTC, szmejk commented on src/components/DataGrid/DataGridFilters/FilterKeyMapper.test.ts
> +      it("should raise error on wrong column for getValues", () => {
for getKeyPairs

2024-10-17 08:50 UTC, lubos-tomsa commented on src/components/DataGrid/DataGridFilters/FilterKeyMapper.test.ts
> +    it("should provide values", () => {
fixed

2024-10-17 08:51 UTC, lubos-tomsa commented on src/components/DataGrid/DataGridFilters/FilterKeyMapper.test.ts
> +      it("should raise error on wrong column for getValues", () => {
fixed

2024-10-18 13:30 UTC, szmejk approved these changes

2024-10-18 13:44 UTC, merged