UCL-555 SideSheet component
onewelcome/react-lib-components pull request #741
Opened 2024-10-15 07:06 UTC by szmejk

2024-10-18 12:02 UTC, MichalGorskiOnegini commented on src/components/Notifications/SlideInModal/SlideInModal.tsx
> + * @deprecated use the new `SideSheet` component
Please, add a deprecation message to SlideInModal storybook as well, would be nice to add it also to the navigation in SB.

2024-10-18 12:07 UTC, MichalGorskiOnegini commented on stories/Notifications/SideSheet/SideSheet.mdx
> +- `onClose` - callback that should be called when `SideSheet` closes
These three properties look weird compared to Props generate by SB. You should probably add some link here to Modal props that those extend. Also, I can see that we have now: `open`, `onClose`, handleProps: {`onOpen`: ()=> , {`onClose`: ()=>..... is that on purpose? Looks confusing

2024-10-18 12:10 UTC, MichalGorskiOnegini commented on stories/Notifications/SideSheet/SideSheet.mdx
> +- `onClose` - callback that should be called when `SideSheet` closes
I think I finally get it. If that is because handleProps is basically a props of an handle button, please rename it to handleButtonProps

2024-10-18 12:13 UTC, MichalGorskiOnegini commented on src/components/Notifications/BaseModal/BaseModal.tsx
> +  hideBackdrop?: boolean;
What is backdrop? I played with the props and I have no idea what it does :(

2024-10-18 12:32 UTC, MichalGorskiOnegini commented on src/components/Notifications/SideSheet/SideSheet.tsx
> +      {handleProps && !open && (
I could not make it null, so SB would not render it using SB controls. Can you take a look?

2024-10-22 07:19 UTC, szmejk commented on src/components/Notifications/SideSheet/SideSheet.test.tsx
> +describe("SideSheet should render", () => {
done

2024-10-22 07:19 UTC, szmejk commented on src/components/Notifications/SideSheet/SideSheet.test.tsx
> +  it("renders without crashing", () => {
done

2024-10-22 07:19 UTC, szmejk commented on src/components/Notifications/SideSheet/SideSheet.test.tsx
> +  it("makes modal content's container visible after opening transition ends", () => {
done

2024-10-22 07:19 UTC, szmejk commented on src/components/Notifications/SideSheet/SideSheet.test.tsx
> +const createSideSheet = (params?: (defaultParams: Props) => Props) => {
done

2024-10-22 07:19 UTC, szmejk commented on src/index.ts
> +export { SideSheet } from "./components/Notifications/SideSheet/SideSheet";
done

2024-10-22 07:19 UTC, szmejk commented on src/components/Notifications/SlideInModal/SlideInModal.tsx
> + * @deprecated use the new `SideSheet` component
done

2024-10-22 07:19 UTC, szmejk commented on stories/Notifications/SideSheet/SideSheet.mdx
> +- `onClose` - callback that should be called when `SideSheet` closes
done

2024-10-24 07:26 UTC, MichalGorskiOnegini requested changes

2024-10-24 07:26 UTC, MichalGorskiOnegini commented on src/components/Notifications/SideSheet/SideSheet.tsx
> +export interface Props extends ModalProps {
As discussed -> lets omit the props we know for sure won't have any effect for readability

2024-10-28 15:28 UTC, MichalGorskiOnegini approved these changes

2024-10-28 15:28 UTC, merged