UC-73 Fixes for FileUpload
onewelcome/react-lib-components pull request #743
Opened 2024-10-24 04:34 UTC by pawel-napieracz

Exposed useUploadFile and some of FileUpload's interfaces
Fixed parsing maxSize
Fixed filename alignment
Extend useUploadFile hook
Changed error message handler

2024-10-25 10:59 UTC, MichalGorskiOnegini requested changes

2024-10-25 10:59 UTC, MichalGorskiOnegini commented on src/hooks/useUploadFile.test.ts
> +    // expect(file.error).toEqual(error);
? :D

2024-10-25 10:59 UTC, MichalGorskiOnegini commented on src/index.ts
>  export { FileUpload } from "./components/Form/FileUpload/FileUpload";
While at it, can you break the line here and introduce a comment e.g /* FileUpload */ ?

2024-10-28 05:36 UTC, pawel-napieracz commented on src/hooks/useUploadFile.test.ts
> +    // expect(file.error).toEqual(error);
I fixed it with second push ;)

2024-10-28 05:39 UTC, pawel-napieracz commented on src/index.ts
>  export { FileUpload } from "./components/Form/FileUpload/FileUpload";
added

2024-10-28 08:53 UTC, MichalGorskiOnegini approved these changes

2024-10-28 15:18 UTC, MichalGorskiOnegini approved these changes

2024-10-28 15:19 UTC, merged