UCL-454 MultiSelect enhancement v2
onewelcome/react-lib-components pull request #744
Opened 2024-11-15 15:07 UTC by lubos-tomsa

1. Options element is now placed with respect to the height of the select element (when more options make it grow)
2. `useMultiSelect` serves all use cases I found, so I did not follow the original design with `onAdd/onRemove` (see https://onewelcome.atlassian.net/browse/UCL-454 ). I can add such possibility, but that would IMO need justification based on a clear real-life example. Regarding storybook, I replaced old .mdx documentation examples with the new code using `useMultiSelect`. However, these are additional stories, I did not remove the old stories. I think it's ok to remove the old stories, but let me know what you think. 

What's missing: I did not unit test scenarios of wrong/missing parameters for `useMultiSelect`, neither I politely check whether mandatory input parameters are missing. That should be probably added.

2024-11-20 09:38 UTC, pawel-napieracz reviewed
I haven't finished yet. Just check my initial comments :)

2024-11-20 09:38 UTC, pawel-napieracz commented on src/components/Form/Select/SingleSelect/Select.tsx
> +        <div className="list-wrapper-container">
and here we don't need to render this list above and below select (input) as you did in MultiSelect?

2024-11-20 09:38 UTC, pawel-napieracz commented on src/components/Form/Select/Select.interfaces.ts
> +}
nice

2024-11-20 09:38 UTC, pawel-napieracz commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    const result = useMultiSelect({
please rewrite test to use renderHook.
If someone adds some hook specific or react-specific stuff into that hook, tests won't work anymore :(.

2024-11-20 09:38 UTC, pawel-napieracz commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +      setAllOptions: newOptions => (newAllOptions = newOptions),
```suggestion
      setAllOptions: newOptions => {newAllOptions = newOptions},
```

2024-11-20 09:38 UTC, pawel-napieracz commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +      setPickedOptions: newOptions => (newPickedOptions = newOptions)
```suggestion
      setPickedOptions: newOptions => {newPickedOptions = newOptions}
```

2024-11-20 09:38 UTC, pawel-napieracz commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    );
I would do the ExampleComponent that uses MultiSelect not to have that simulated/mocked.

2024-11-20 09:38 UTC, pawel-napieracz commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +      setPickedOptions: newOptions => (newPickedOptions = newOptions)
```suggestion
      initialOptions: allOptions,
      allOptions,
      setAllOptions: newOptions => {newAllOptions = newOptions},
      pickedOptions,
      setPickedOptions: newOptions => {newPickedOptions = newOptions}
```

2024-11-20 09:38 UTC, pawel-napieracz commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    // next render after the custom option was added
please split the test with `// given, // when //then`. Try to not add unnecessary comments

2024-11-20 09:38 UTC, pawel-napieracz commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +      setAllOptions: newOptions => (newAllOptions = newOptions)
I'd omit it then :)

2024-11-20 09:38 UTC, pawel-napieracz commented on stories/Form/Elements/MultiSelect.stories.tsx
> +export const MultiSelectUseWithAddNew = (args => {
it's not used anywhere

2024-11-20 09:38 UTC, pawel-napieracz commented on stories/Form/Elements/MultiSelect.stories.tsx
> +export const MultiSelectUseAsEditableList = (args => {
same

2024-11-20 09:38 UTC, pawel-napieracz commented on stories/Form/Wrapper/MultiSelectWrapper.mdx
> +      {!args.stickToBottom ? <div style={{ height: "7rem" }}></div> : undefined}
why it's in the example :D?

2024-11-20 11:59 UTC, lubos-tomsa commented on stories/Form/Wrapper/MultiSelectWrapper.mdx
> +      {!args.stickToBottom ? <div style={{ height: "7rem" }}></div> : undefined}
This is to show expansion of the options above the multiselect, there was no explicit story to show that

2024-11-20 12:01 UTC, lubos-tomsa commented on stories/Form/Elements/MultiSelect.stories.tsx
> +export const MultiSelectUseWithAddNew = (args => {
it's not in the mdx for MultiSelect, but there is a link to MultiSelectWrapper doc.
It's not used but it still shows and allows us to see it - I think this way it was done in many other cases in UCL.
I originally thought I will duplicate also mdx content with the wrapper mdx, but then I decided to just link it.
Maybe it's a good idea to duplicate it.

2024-11-20 12:01 UTC, lubos-tomsa commented on stories/Form/Elements/MultiSelect.stories.tsx
> +export const MultiSelectUseAsEditableList = (args => {
same

2024-11-20 12:02 UTC, lubos-tomsa commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +      setAllOptions: newOptions => (newAllOptions = newOptions)
It's there exactly to test the behavior, that's why it must be there, see how it's tested

2024-11-20 12:07 UTC, lubos-tomsa commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    // next render after the custom option was added
Frankly, I can try to split some tests like that, but some tests are testing 2 rounds of state changes. I am not a fan of strict given/when/then marking when clearly there are cases where it does not fit.

The comments are necessary here in my opinion for the person reading the test to understand what is going on. I am not a fan of unnecessary comments too, but again, not strictly. The code has to be understandable fast, and sometimes just naming and structuring the code is not helpful enough, sometimes it can make situation even harder.

2024-11-20 12:10 UTC, lubos-tomsa commented on src/components/Form/Select/SingleSelect/Select.tsx
> +        <div className="list-wrapper-container">
maybe it would be better but here I left the original idea, because for some reason it didn't work the same as with multi-select and I didn't want to put too much time in it, soo here it's the old positioning, only differently written
`bottom: listPosition === Position.Above ? "2.75rem" : "initial"`

2024-11-20 12:39 UTC, lubos-tomsa commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +      setAllOptions: newOptions => (newAllOptions = newOptions),
in fact it would have to be 
```
      setAllOptions: newOptions => {
        newAllOptions = newOptions;
      },
```
because of prettier. I'd keep the single-line (), it's quite common for single statements

2024-11-20 13:40 UTC, lubos-tomsa commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +      setPickedOptions: newOptions => (newPickedOptions = newOptions)
same

2024-11-20 18:31 UTC, lubos-tomsa commented on stories/Form/Wrapper/MultiSelectWrapper.mdx
> +      {!args.stickToBottom ? <div style={{ height: "7rem" }}></div> : undefined}
sorry, taking back - it has nothing to do in the example :D

2024-11-21 06:35 UTC, pawel-napieracz requested changes

2024-11-21 06:35 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.test.ts
> +  it("should handle editable-list scenario from identity-broker-ui", () => {
please describe test without mentioning it's from ibui

2024-11-21 06:35 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +  const onAddNew = args.onAddNew;
```suggestion
export const useMultiSelect: UseMultiSelect = ({
  initialOptions,
  pickedOptions,
  allOptions = pickedOptions,
  setPickedOptions,
  setAllOptions = setPickedOptions,
  onAddNew
}) => {
```

2024-11-21 06:35 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +            setAllOptions(allOptions.filter(value => value !== option.value));
In all optional callback add `?.`
```suggestion
            setAllOptions?.(allOptions.filter(value => value !== option.value));
```

2024-11-21 06:35 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +      .options;
```suggestion
    const htmlOptions =  e.currentTarget.options;
```

2024-11-21 06:35 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.test.ts
> +describe("useMutiSelect", () => {
i'd more focus on testing adding in each test separately:
- selecting new option
- deselecting option
-  etc...

2024-11-21 06:35 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +          const isInInitialOptions = initialOptions.includes(option.value);
you can remove first if and do the magic with optional chaining:
`initialOptions?.includes...`

2024-11-21 06:35 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +    if (trimmedValue.length == 0 || allOptions.includes(trimmedValue)) {
```suggestion
    if (trimmedValue.length === 0 || allOptions.includes(trimmedValue)) {
```

2024-11-21 06:35 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +    }
```suggestion
      onAddNew?.(trimmedValue);
```

2024-11-21 06:35 UTC, pawel-napieracz commented on stories/Form/Elements/MultiSelect.mdx
> +    </MultiSelectComponent>
if you do that many examples maybe one can use {optionElements} returned from hook?

2024-11-21 13:02 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/MultiSelect.test.tsx
> +    const { select, button, container } = createMultiSelect();
This was something I played with quite long and I am not sure what happened there, but essentially the problem was that the original test did not really re-render after click, so it was not possible to check positions of the elements. The dropdownWrapper was apparently an invalid element after the click, that's why I query it again using container.

2024-11-21 13:08 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/MultiSelect.test.tsx
> +    const dropdownWrapper2 = select.querySelector(".list-wrapper");
I'm not sure if that is possible, since there is a re-render. Could you elaborate on how to do it in this case?

2024-11-21 13:09 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/MultiSelect.test.tsx
> +    const dropdownWrapper2 = select.querySelector<HTMLDivElement>(".list-wrapper")!;
same

2024-11-21 13:21 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.test.ts
> +  it("should handle editable-list scenario from identity-broker-ui", () => {
ok

2024-11-21 13:35 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +          const isInInitialOptions = initialOptions.includes(option.value);
yes, I was thinking about this also - this was just copy pasta, given the time it took already I was not aiming to be good boy scout  :D

2024-11-21 13:38 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +            setAllOptions(allOptions.filter(value => value !== option.value));
Perfect! I didn't know this syntax, I actually wanted to use it somewhere else but then was too lazy to search for it

2024-11-21 13:43 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +    if (trimmedValue.length == 0 || allOptions.includes(trimmedValue)) {
I think here it does not matter, because length is always a number, but why not.

2024-11-21 13:45 UTC, lubos-tomsa commented on stories/Form/Elements/MultiSelect.mdx
> +    </MultiSelectComponent>
this was exactly one of the ideas, I wonder what will you think about the other one :D but I will do code fixes first

2024-11-21 14:04 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +      .options;
Not that I didn't try... this is how it was in the browser also, that's the reason for the ugliness

![image](https://github.com/user-attachments/assets/26a157e8-dd46-4bb7-b675-af4dff5d74c9)

2024-11-21 14:20 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +          const isInInitialOptions = initialOptions.includes(option.value);
But unfortunately not usable here, because of the negation

2024-11-21 18:16 UTC, lubos-tomsa commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    );
Ok, that's a different kind of test (more towards visual) than what I had in mind (like unit testing of the particular functionality), but I will take a look on that and maybe I can keep a bit of both.

2024-11-21 18:30 UTC, lubos-tomsa commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +      setPickedOptions: newOptions => (newPickedOptions = newOptions)
The same as previous, prettier would expand it

2024-11-21 18:31 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.test.ts
> +  it("should handle editable-list scenario from identity-broker-ui", () => {
done

2024-11-21 18:31 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +  const onAddNew = args.onAddNew;
done

2024-11-21 18:31 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +            setAllOptions(allOptions.filter(value => value !== option.value));
done

2024-11-21 18:32 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +    if (trimmedValue.length == 0 || allOptions.includes(trimmedValue)) {
done

2024-11-21 19:20 UTC, lubos-tomsa commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    const result = useMultiSelect({
done

2024-11-27 12:17 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +      .options;
weird. It should be there. Maybe it's because of how you create the event in useMultiSelect.test.ts?

2024-11-27 13:11 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +          const isInInitialOptions = initialOptions.includes(option.value);
is it. See 
```
const isInInitialOptions = initialOptions?.includes(option.value);
if (!isInInitialOptions) {
  setAllOptions(allOptions.filter(value => value !== option.value));
}
```

2024-11-27 13:50 UTC, pawel-napieracz commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    // next render after the custom option was added
Regarding comments:
```Readable Code Should Replace Comments: Robert C. Martin ("Uncle Bob") in Clean Code emphasizes that clear, self-explanatory code reduces the need for comments. Comments often indicate that the code itself could be improved—for example, by using better variable names or breaking functions into smaller, logical pieces```
So please play with variable names & extracting something to helper methods (like selecting/deselecting something (you have comment also there)) within this test like `selectOption = () => {}` or `deselectOption = () => {}`.

Regarding: given, when, then
In our way of testing, we sometimes can't do a unit test, so we are "forced" to do more in 1 test. So we need these keywords to separate preparation phase from testing.

2024-11-27 13:51 UTC, pawel-napieracz commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    );
not pushing. Just showing you can't avoid mocking request and dom :).

2024-11-27 14:08 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/MultiSelect.test.tsx
> +    const dropdownWrapper2 = select.querySelector(".list-wrapper");
you can change createMultiSelect to return the container you want. But you said that you had issues with getting handler after rerender.
In this case you can leave it as it.

But what I don't like and we basically avoiding is checking classes in tests. Classes are mostly likely internal API which we don't want to test.

I'd remove it from this test and visual test it :)

2024-11-27 14:10 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/MultiSelect.test.tsx
> +    const customSelect = container.querySelector(".custom-select")!;
yea :)

2024-11-27 14:12 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/MultiSelect.test.tsx
> +    const { select, button, container } = createMultiSelect();
ok, got it

2024-11-27 14:14 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.test.ts
> +describe("useMutiSelect", () => {
You can group groups in test.
In one group you can do tests for 1 usecase, in another group for second usecase

2024-11-28 13:15 UTC, pawel-napieracz requested changes

2024-11-28 13:15 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +          if (!initialOptions.includes(option.value)) {
please don't do 3th lvl nesting of conditions.
Maybe simply `if (initialOptions && !initialOptions.includes(option.value)) {`?

2024-11-28 13:15 UTC, pawel-napieracz commented on stories/Form/Elements/MultiSelect.stories.tsx
> +MultiSelectWithoutSearch.play = playExpand;
we can have it not expanded so we can show it nicely in docs (MDX) :)

2024-11-28 13:15 UTC, pawel-napieracz commented on stories/Form/Elements/MultiSelect.stories.tsx
> +MultiSelectWithoutSearch.play = playExpand;
Somethin to discuss. We mainly just call it `ComponentName`. That's why we imported component with sufix Component to not have clash with exporting this story :).

2024-11-28 13:15 UTC, pawel-napieracz commented on stories/Form/Elements/MultiSelect.stories.tsx
> +} from "../../../src/components/Form/Select/MultiSelect/MultiSelect";
```suggestion
import {
  MultiSelect
} from "../../../src/components/Form/Select/MultiSelect/MultiSelect";
```

2024-11-28 13:15 UTC, pawel-napieracz commented on stories/hooks/useMultiSelect.mdx
> +In an advanced scenario (**#2**) it allows you to automatically handle `MultiSelect`'s `onAddNew` functionality, where it not only adds the new option, but it also takes care about removing such a cu
```suggestion
In an advanced scenario (**#2**) it allows you to automatically handle `MultiSelect`'s `onAddNew` functionality, where it not only adds the new option, but it also takes care about removing such a custom option from the list of all options when the user unpicks it.
```

2024-11-28 13:15 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +  setPickedOptions,
can it really work without `setPickedOptions`? I'd make it required and edit docs

2024-11-28 13:15 UTC, pawel-napieracz commented on stories/hooks/useMultiSelect.mdx
> +  - _(mandatory for scenarios #1 and #2, not mandatory for scenario #3, where the user doesn't really pick from a list of options; istead they only change the picked options)_
```suggestion
  - _(mandatory for scenarios #1 and #2, not mandatory for scenario #3, where the user doesn't really pick from a list of options; instead they only change the picked options)_
```

2024-11-28 14:45 UTC, lubos-tomsa commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    // next render after the custom option was added
As I said, I do very much agree with having self explanatory code instead of comments where it makes sense. 

(1) Regading the example of change you propose, I would not personally feel better about the code if I extracted a function to replace these lines of an unit test

```
// unpick an option
selectElement.options.item(2)!.selected = false;
```
by e.g.
```
 const unpickOption = (index: number) => (selectElement.options.item(index)!.selected = false);
...
unpickOption(2);
```

It's doable, it's not in my opinion better, unless there are at least 2 cases of unpicking in the unit test.

(2) Regarding other, more important comment, and this also related to the given/when/then template, 

```
// next render after the custom option was added
```
this comment visually splits 2 factual unit test rounds which this test is based on. Without such division, it
would not be clear what's going on, unless we split the unit test to pieces, which was my point [here]( https://github.com/onewelcome/react-lib-components/pull/744#discussion_r1852050876)

The point I was making there was not about grouping (nested describes), but about the fact, that if I remove the splitting comment, I would have to put the parts of the test to separate tests, which are testing 2 time portions of the same interaction:

1. Given the initial state, when user adds a custom value, then there is a new option in `allOptions` etc.
2. Given the exactly expressed `initialOptions` and `allOptions`, when user deletes one of the values (the one we crafted as custom by 
being in `allOptions` but not in `initialOptions`), it is removed also from `allOptions`

Which is of course not wrong at all. In most similar cases I would recommended splitting like this.
But in this case in my opinion it would be harder to read than a single test, where you both add and delete the custom option, particularly
because (without another comment), the progammer would have to visually compare the option lists and infer what we mean by the setup. Or, this would have to be very precisely explained in the `it` text.

(3) Regarding comments like this
```
// custom option removed also from all options
expect(newAllOptions).toEqual(["A", "B", "C", "D"]);
```
I really prefered readability. Just leaving the line there would not help to make the code more readable and maintainable.

For all 3 points: If we are now on the same page about what would change and how, I can do it the way you prefer and we will see - let me know.

2024-11-28 18:56 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/MultiSelect.test.tsx
> +    const customSelect = container.querySelector(".custom-select")!;
you are absolutely right, done

2024-11-28 19:10 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +          const isInInitialOptions = initialOptions.includes(option.value);
When `initialOptions` is `undefined` (i.e. there is no support for automatic custom options and we don't want to remove the custom value from `allOptions`), `isInInitialOptions` is `undefined`, hence, `!isInitialOptions` is `true` and we remove the option from all options even though it was not a custom option.

Thankfully, this is also caught by 2 unit tests.
This is a result of the basic one:
```
  ● useMutiSelect › should handle basic usage scenario

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 3

      Array [
    -   "not called",
    +   "A",
    +   "B",
    +   "D",
      ]

      55 |
      56 |     expect(newPickedOptions).toEqual(["B", "D"]);
    > 57 |     expect(newAllOptions).toEqual(["not called"]);
```

2024-11-28 19:12 UTC, lubos-tomsa commented on stories/Form/Elements/MultiSelect.mdx
> +    </MultiSelectComponent>
so the other idea was to make examples exactly duplicate their stories and making this fact explicitly visible, e.g. by using prefix `Example-`

this part was not implemented in the end (I was in the middle and reverted it), otherwise it should be done

2024-11-28 19:21 UTC, lubos-tomsa commented on stories/Form/Elements/MultiSelect.stories.tsx
> +MultiSelectWithoutSearch.play = playExpand;
I thought we want to see it expanded in MDX and to have the space there (as I wrote in Slack)

2024-11-28 19:44 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +  setPickedOptions,
Yes, I was exactly thinking about that, but then I thought that people might want to use only part of the functionality - generation of options. It's actually used like that in the test which tests this scenario itself - `it("should generate option elements"`. I'm not sure how often that would be used, but it felt to me that it's better to leave this up to the consumer. But I'm approx. 50:50 on this, so just let me know considering this and I can make it mandatory.

2024-11-28 19:47 UTC, lubos-tomsa commented on stories/hooks/useMultiSelect.mdx
> +  - _(mandatory for scenarios #1 and #2, not mandatory for scenario #3, where the user doesn't really pick from a list of options; istead they only change the picked options)_
done

2024-11-28 19:48 UTC, lubos-tomsa commented on stories/hooks/useMultiSelect.mdx
> +In an advanced scenario (**#2**) it allows you to automatically handle `MultiSelect`'s `onAddNew` functionality, where it not only adds the new option, but it also takes care about removing such a cu
done

2024-11-28 19:48 UTC, lubos-tomsa commented on stories/Form/Elements/MultiSelect.stories.tsx
> +} from "../../../src/components/Form/Select/MultiSelect/MultiSelect";
done

2024-11-28 19:50 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +          if (!initialOptions.includes(option.value)) {
very true, I removed the explanatory variable from the copy-pasted code, because the code seemed self explanatory enough, but forgot to also simplify it

done

2024-11-28 20:04 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.test.ts
> +    ));
cool idea, but it doesn't seem to work. It behaves like if I called the first render again, so a test is failing.. I'd have to dig deeper to understand what exactly goes on there

2024-11-28 20:04 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/MultiSelect.test.tsx
> +import { MultiSelect, MultiSelect as MultiSelectComponent } from "./MultiSelect";
done

2024-11-28 20:04 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.test.ts
> +describe("useMutiSelect", () => {
see in previous reply

2024-11-28 20:05 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/MultiSelect.test.tsx
> +    const dropdownWrapper2 = select.querySelector(".list-wrapper");
done

2024-11-28 20:10 UTC, lubos-tomsa commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    );
ok perhaps I didn't understand how that should look like, can you elaborate?

2024-11-28 20:11 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +      .options;
But as I said, I remember the same issue from testing it in the browser. I can double check, but this was really not something I did because of the unit test.

2024-11-29 05:59 UTC, pawel-napieracz commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    // next render after the custom option was added
1. If you can avoid comments, do everything to avoid them. It's easier to work with code than with comments.

2. It's nothing bad to split your test into 2. It's also nothing bad to keep it as is. Look at e.g. `"should focus through list items and select on enter press"` test. You will see that there is a lot happening inside a test. Just group it with many `//when` `//then`. I tried to do that, and I found out that it's better to split that test.
```
it("should handle creation of custom option E", () => {
    const allOptions = ["A", "B", "C", "D"];
    const initialOptions = [...allOptions];
    const pickedOptions = ["B", "C"];
    const setAllOptionsMock = jest.fn();
    const setPickedOptions = jest.fn();
    const { result } = renderHook(() =>
      useMultiSelect({
        initialOptions,
        allOptions,
        pickedOptions,
        setAllOptions: setAllOptionsMock,
        setPickedOptions: setPickedOptions
      })
    );

    act(() => {
      result.current.onAddNew("E");
    });

    const expectedPickedOptionsWithNewE = ["B", "C", "E"];
    expect(setPickedOptions).toHaveBeenCalledWith(expectedPickedOptionsWithNewE);
    const expectedAllOptionsWithNewE = ["A", "B", "C", "D", "E"];
    expect(setAllOptionsMock).toHaveBeenCalledWith(expectedAllOptionsWithNewE);
  });

  it("should handle deletion of custom added option E", () => {
    const allOptions = ["A", "B", "C", "D", "E"];
    const initialOptions = ["A", "B", "C", "D"];
    const pickedOptions = ["B", "C", "E"];
    const setAllOptionsMock = jest.fn();
    const setPickedOptions = jest.fn();
    const { result } = renderHook(() =>
      useMultiSelect({
        initialOptions,
        allOptions,
        pickedOptions,
        setAllOptions: setAllOptionsMock,
        setPickedOptions: setPickedOptions
      })
    );


    act(() => {
      const { event: eventForOptionERemoval } = prepareOptionSelection(
        allOptions,
        optionValue => pickedOptions.includes(optionValue) && optionValue !== "E"
      );
      result.current.handleOptionChange(eventForOptionERemoval);
    });

    const expectedPickedOptionsWithoutE = ["B", "C"];
    expect(setPickedOptions).toHaveBeenCalledWith(expectedPickedOptionsWithoutE);
    const expectedAllOptionsWithoutE = ["A", "B", "C", "D"];
    expect(setAllOptionsMock).toHaveBeenCalledWith(expectedAllOptionsWithoutE);
  });
```
But you may just add //when //then.

3. Sometimes I see that ppl uses this. I also use it when I want to have more descriptive things
```    
const expectedAllOptionsWithoutE = ["A", "B", "C", "D"];
expect(setAllOptionsMock).toHaveBeenCalledWith(expectedAllOptionsWithoutE);
```

2024-11-29 06:12 UTC, pawel-napieracz commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    );
```const [allOptions, setAllOptions] = useState<string[]>(["A", "B", "C", "D"]);
      const [pickedOptions, setPickedOptions] = useState<string[]>(["B", "C"]);

      const { handleOptionChange } = useMultiSelect({
        allOptions,
        setAllOptions,
        pickedOptions,
        setPickedOptions
      });

      return (
        <select multiple={true} onChange={handleOptionChange}>
          {allOptions.map(option => (
            <option value={option}>{option}</option>
          ))}
        </select>
      );
    };

    const { getByRole } = render(<ExampleWithMultiSelectHook />);
    //do whatever you want and check what options are inside select :) 
```
This way, you can test the hook as closely as possible for real usage. It's just an idea. Your tests are also fine, but you never know if you prepare event in good way, and if you want to change implementation you need to change tests, but what it test is not changed. So you can break test because you used some property from event that you haven't mocked.

2024-11-29 06:16 UTC, pawel-napieracz commented on stories/Form/Elements/MultiSelect.stories.tsx
> +MultiSelectWithoutSearch.play = playExpand;
Ok. If everyone agrees, I'll also be okay with it.

2024-11-29 06:18 UTC, pawel-napieracz commented on stories/Form/Elements/MultiSelect.stories.tsx
> +MultiSelectWithoutSearch.play = playExpand;
please use `. storyName` prop then

2024-11-29 06:19 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +  setPickedOptions,
I don't think that someone uses MultiSelect with only generating options from useMultiSelect :). If I'd be Select maybe that could be an option.
 I'd opt for making that mandatory.

2024-11-29 12:30 UTC, pawel-napieracz commented on stories/Form/Elements/MultiSelect.stories.tsx
> +MultiSelectWithoutSearch.play = playExpand;
so I want to make the change you did to be `internal` and in storybook we can display different name for that `basic` story using SB's configuration option like this: `MultiSelectWithoutSearch.storyName = "MultiSelect"`

2024-11-29 19:00 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +      .options;
So I dug into this. I don't remember exactly what was the case `currentTarget` was missing originally and in the storybook it is present, but based on some research I found a case when it is constantly `null` for me, and that's when the handler is called asynchronously, because there is some kind of optimization based in reusing event objects in React. So I think the best option is to add argument validation for this, throwing a clear explanatory error, what might have happened.

If you are ok with this solution, I will create a unit test for it.

2024-11-29 19:16 UTC, lubos-tomsa commented on stories/Form/Elements/MultiSelect.stories.tsx
> +MultiSelectWithoutSearch.play = playExpand;
I removed play for the first story, because it was not present in master. 

So to be sure I compared behavior of MultiSelect stories between master and this branch, and I found another problem which was not handled well, and that is adding a new custom option without search. This is now fixed, including unit test (still old style, no example component).

2024-11-29 19:16 UTC, lubos-tomsa commented on stories/Form/Elements/MultiSelect.stories.tsx
> +MultiSelectWithoutSearch.play = playExpand;
done

2024-12-02 05:25 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +      .options;
`currentTarget` is always present when you have event sent by element (like clicking ON BUTTON, selecting option FROM SELECT, etc. :) ).
I'd go for `currentTarget`.

2024-12-02 05:26 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.test.ts
> +describe("useMutiSelect", () => {
sorry, which one?

2024-12-02 05:29 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +  setPickedOptions,
Can you make it required or you want to kept it optional?

2024-12-02 05:35 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +    }
adding this at the beginning and then at the end doesn't look good. And why are you calling `onAddNew` with  `""` if value is null or undefined?
```
    const trimmedValue = (value ?? "").trim();
    if (trimmedValue.length === 0 || allOptions.includes(trimmedValue)) {
      onAddNew.?(value);
      return;
    }
    setAllOptions?.([...allOptions, trimmedValue]);
    setPickedOptions?.([...pickedOptions, trimmedValue]);
    onAddNew?.(trimmedValue);
```

2024-12-02 05:43 UTC, pawel-napieracz requested changes
Still some open questions and code to fix

2024-12-02 06:46 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +      .options;
Yet I experienced it being null or undefined in the browser, and there are cases when it can be null (I reproduced it with async call of the handler function), some of them as I understood having something to do with event pooling in React 16, some just as a feature by the browser.
https://stackoverflow.com/questions/66085763/why-currenttarget-value-is-null

Maybe you didn't notice, I am using currentTarget now, it's just now being validated, to make life of the consumer easier.
So you say, don't validate currentTarget, just let it crash on "Cannot read properties of undefined ..." when this happens?

2024-12-02 06:49 UTC, lubos-tomsa commented on src/components/Form/Select/MultiSelect/useMultiSelect.test.ts
> +describe("useMutiSelect", () => {
[here](https://github.com/onewelcome/react-lib-components/pull/744#discussion_r1862322991), but it's clear now

2024-12-02 08:18 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +      .options;
Ok. I don't want to force you to use `currentTarget`. I just wanted to get that options without casting and currentTarget worked for me.
But I can't find more then 1 usage of `currentTarget` in our code. We are using `target`. I didn't know why it's not working there. And I realize that you are using wrong type that narrow the output types.
Please change it to `React.ChangeEvent<HTMLSelectElement>` and now you can use `e.target.options`. I hope that will work.

2024-12-02 08:22 UTC, pawel-napieracz commented on src/components/Form/Select/MultiSelect/useMultiSelect.tsx
> +    }
the missing return was a key.

You're right.

2024-12-03 13:31 UTC, lubos-tomsa commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    // next render after the custom option was added
done

2024-12-04 05:28 UTC, pawel-napieracz commented on src/components/Form/Wrapper/MultiSelectWrapper/useMultiSelect.test.ts
> +    );
yeap

2024-12-04 05:45 UTC, pawel-napieracz requested changes
when it comes to code [approved].
When it comes to look:
- 4px space between dropdown list and input is now missing: https://www.chromatic.com/test?appId=63e21de9a62cab5a8a3e31c7&id=674fe83e11f39638ec361567
-please remove additional space in select wrapper stories
https://www.chromatic.com/test?appId=63e21de9a62cab5a8a3e31c7&id=674fe83e11f39638ec36158c

2024-12-09 13:16 UTC, merged