UCL-452 | Form fields need a "read-only" state
onewelcome/react-lib-components pull request #745
Opened 2024-11-18 10:17 UTC by ambujThalesOW

I have verified couple of component with identity-broker-ui and it is working great.
<img width="1478" alt="image" src="https://github.com/user-attachments/assets/e8449764-a375-4476-a4d0-a68c4a0648c6">

2024-11-21 09:51 UTC, MichalGorskiOnegini requested changes

2024-11-21 09:51 UTC, MichalGorskiOnegini commented on src/components/withReadOnly.tsx
> +          required={readOnlyView ? false : required}
I don't think we should pass anything else other than data-readonlyview

2024-11-21 09:51 UTC, MichalGorskiOnegini commented on src/components/Form/Wrapper/TextareaWrapper/TextareaWrapper.tsx
> +  const getChildren = () => {
Same as in the raw component, please rename the function and get rid of the hardcoded classnames

2024-11-22 03:28 UTC, ambujThalesOW commented on src/components/withReadOnly.tsx
> +          required={readOnlyView ? false : required}
in Readonly view, we are not suppose to show required field identifier (red asterisk) so for that reason I need to pass it otherwise I have to handle it by CSS(`display: none`)

2024-11-22 03:37 UTC, ambujThalesOW commented on src/components/withReadOnly.tsx
> +  disabled?: boolean;
as we are keeping form elements( input, select, etc) and making them readonly so we have to disable them to make it non-editable

2024-11-22 03:42 UTC, ambujThalesOW commented on src/components/withReadOnly.tsx
> +      const addReadOnlyAttribute = (childNodes: ReactNode): ReactNode => {
It is enough capable of it but here my intention was if any any scenario we have children or implement something in future which needed then we don't need to come back here & make this logic compatible though I didn't find exact usecase as of now... but yes we can remove it for now. There is no benefit of keeping code when we are not sure to have use case in future too.

2024-11-22 03:45 UTC, ambujThalesOW commented on src/components/Form/Checkbox/Checkbox.module.scss
> +// Read Only Mode Styling ONLY
Sure, as I mentioned earlier that I kept `comments` for dev/review purpose only & suppose to remove before merge.

2024-11-22 03:47 UTC, ambujThalesOW commented on src/components/Form/Textarea/Textarea.tsx
>  import classes from "./Textarea.module.scss";
Indded. Why this didn't hit in my mind ;)

2024-11-22 03:49 UTC, ambujThalesOW commented on src/components/Form/Textarea/Textarea.tsx
>  import { FormElement } from "../form.interfaces";
Aye Aye Captain!

2024-12-05 13:33 UTC, MichalGorskiOnegini requested changes

2024-12-05 13:33 UTC, MichalGorskiOnegini commented on src/components/Form/Wrapper/SelectWrapper/SelectWrapper.tsx
> +export const SelectWrapper = withReadOnly(React.forwardRef(SelectWrapperComponent));
I'm able to change the value of the select when navigating with keyboard. Please fix here and validate other cases.

2024-12-05 13:33 UTC, MichalGorskiOnegini commented on stories/Form/Wrapper/CheckboxWrapper.stories.tsx
> +export const CheckboxesWithReadOnlyMode = CheckboxesTemplate.bind({});
The focus state on the checked checkbox is not visible (but seems to be working)

2024-12-05 13:33 UTC, MichalGorskiOnegini commented on stories/Form/Elements/FileItem.stories.tsx
>  FileItemReadOnly.args = {
In this case it's the download button that gets the focus. It's not ok, because what is being read by voice over is: "The link you have visited: Download" 

it should be the entire FileItem that gets the focus, probably with some aria attribute passed so the user understand it's an uploaded file

2024-12-05 13:33 UTC, MichalGorskiOnegini commented on src/components/Form/FileUpload/FileUpload.tsx
>  const FileUploadComponent: ForwardRefRenderFunction<HTMLInputElement, Props> = (
When I add readOnlyViewMessage, it applies next to "Upload button". This button should not be visible when in the read only mode,

2024-12-05 13:37 UTC, ambujThalesOW commented on src/components/withReadOnly.tsx
> +  required?: boolean;
As per discussion, I am sure it's clear now. Right?

2024-12-05 13:56 UTC, ambujThalesOW commented on src/components/withReadOnly.tsx
> +          required={readOnlyView ? false : required}
hope this one also cleared to you ;)

2024-12-05 14:14 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileUpload.tsx
> +                className={"drag-and-drop-text"}
TBH, I am not sure about side effect of changing it...

2024-12-05 14:16 UTC, ambujThalesOW commented on src/components/Form/Input/Input.tsx
> +  const readOnlyMode = rest["data-readonlyview"] as boolean;
Yes because need to play at component level for specific usecase

2024-12-06 05:15 UTC, ambujThalesOW commented on src/components/Form/FileUpload/FileUpload.tsx
>  const FileUploadComponent: ForwardRefRenderFunction<HTMLInputElement, Props> = (
Yes. It suppose to be in same way.
<img width="880" alt="image" src="https://github.com/user-attachments/assets/2fa9ce71-9335-450d-b09b-aa0694a3f807">

2024-12-06 08:33 UTC, ambujThalesOW commented on src/components/withReadOnly.tsx
> +  if (readOnlyView) {
if you are referring to `if (readOnlyView && helperText) {`  then actually not because in some components we are not using `helperText` so if I will still set to `""` then it start throwing error in console but won't break flow

2024-12-06 08:33 UTC, ambujThalesOW commented on src/components/withReadOnly.tsx
> +    props = { ...props, helperText: "" };
may be not now as I made some changes in same block but do let me know if you still feel same

2024-12-06 08:33 UTC, ambujThalesOW commented on stories/Form/Elements/FileItem.stories.tsx
>  FileItemReadOnly.args = {
isn't fine as it's says Link Download + Uploaded File Name?

2024-12-06 08:33 UTC, ambujThalesOW commented on stories/Form/Wrapper/SelectWrapper.stories.tsx
> +export const SelectWrapperWithReadOnlyMode = Template.bind({});
I didn't get correctly. What could be invalid format/name here?
Is URL & Name in left bar not generating properly? 

<img width="904" alt="image" src="https://github.com/user-attachments/assets/6c79fb1f-34ae-4b54-824e-b410abc96131">

2024-12-11 13:49 UTC, MichalGorskiOnegini approved these changes

2024-12-12 08:09 UTC, MichalGorskiOnegini approved these changes

2024-12-12 09:03 UTC, merged