UCL-563 Data grid datetime picker
onewelcome/react-lib-components pull request #748
Opened 2024-12-04 10:24 UTC by szmejk

2024-12-13 10:55 UTC, MichalGorskiOnegini requested changes

2024-12-13 10:55 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridFilters/DateTimePicker/DateTimePicker.tsx
> +    dateInputPlaceholder: "yyyy-mm-dd hh:mm:ss"
Please, extract to a static and refer to the format in other places (such as above, in the error message)

2024-12-13 10:55 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridFilters/DateTimePicker/DateTimePicker.tsx
> +                <DateTimePickerInputSection
just a thought: 
have you considered using context? So instead of passing the set functions you could operate on the values within the context?

2024-12-13 10:55 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridFilters/DateTimePicker/DateTimePickerInputSection.tsx
> +        style={{ marginTop: 0, maxWidth: "224px" }}
Why passing the style like this?

2024-12-13 10:55 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridFilters/DateTimePicker/DateTimePickerInputSection.tsx
> +        name={"fromDate"}
```suggestion
        name="fromDate"
```

to me it's ok, but @pawel-napieracz hunts me with this :D

2024-12-13 10:55 UTC, MichalGorskiOnegini commented on src/components/DatePicker/DatePicker.tsx
> +          endMonth={new Date(3000, 12)}
A prophecy...

2024-12-13 10:55 UTC, MichalGorskiOnegini commented on stories/DataGrid/DataGrid.stories.tsx
> +};
Please, add the entry with play function that will open the filter

2024-12-13 10:55 UTC, MichalGorskiOnegini commented on src/components/DataGrid/DataGridFilters/DateTimePicker/DateTimePickerCalendarSection.tsx
> +  return (
Some months take more height than others. This makes the entire modal "jump" a little. I don't think it's a big issue but would be nice to discuss with the UX.

2024-12-13 15:11 UTC, szmejk commented on stories/DataGrid/DataGrid.stories.tsx
> +};
done

2024-12-13 15:11 UTC, szmejk commented on src/components/DatePicker/DatePicker.tsx
> +          endMonth={new Date(3000, 12)}
discussed on slack

2024-12-13 15:11 UTC, szmejk commented on src/components/DataGrid/DataGridFilters/DateTimePicker/DateTimePickerInputSection.tsx
> +        name={"fromDate"}
done

2024-12-13 15:11 UTC, szmejk commented on src/components/DataGrid/DataGridFilters/DateTimePicker/DateTimePickerInputSection.tsx
> +        style={{ marginTop: 0, maxWidth: "224px" }}
fixed

2024-12-13 15:11 UTC, szmejk commented on src/components/DataGrid/DataGridFilters/DateTimePicker/DateTimePicker.tsx
> +                <DateTimePickerInputSection
discussed on slack

2024-12-13 15:11 UTC, szmejk commented on src/components/DataGrid/DataGridFilters/DateTimePicker/DateTimePicker.tsx
> +    dateInputPlaceholder: "yyyy-mm-dd hh:mm:ss"
done

2024-12-13 15:12 UTC, szmejk commented on src/components/DataGrid/DataGridFilters/DataGridFilterTag.tsx
> +              Date is <b>{dateTagCaption}</b>
done

2024-12-13 15:12 UTC, szmejk commented on src/components/DataGrid/DataGrid.test.tsx
> +    expect(getAllByText("The format must be yyyy-mm-dd hh:mm:ss")).toHaveLength(2);
done

2024-12-13 15:12 UTC, szmejk commented on src/components/DataGrid/DataGrid.test.tsx
> +
done

2024-12-13 15:12 UTC, szmejk commented on package.json
> +    "date-fns": "^4.1.0"
done

2024-12-19 08:03 UTC, MichalGorskiOnegini approved these changes

2024-12-19 08:16 UTC, merged