UCL-564 Draft
onewelcome/react-lib-components pull request #750
Opened 2024-12-10 09:53 UTC by lubos-tomsa

2024-12-10 10:48 UTC, pawel-napieracz requested changes

2024-12-10 10:48 UTC, pawel-napieracz commented on src/components/ContextMenu/ContextMenu.tsx
> -        anchorEl.current !== (event.target as HTMLElement).parentElement
this one is not checked

2024-12-10 12:39 UTC, lubos-tomsa commented on src/components/ContextMenu/ContextMenu.tsx
> -        anchorEl.current !== (event.target as HTMLElement).parentElement
the implementation checks all inner elements using `myElement.contains(event.target as Node)`

2024-12-12 11:56 UTC, pawel-napieracz approved these changes

2024-12-13 10:13 UTC, pawel-napieracz approved these changes

2024-12-13 10:13 UTC, merged